import { WidgetConfig } from '../types';
import { WIDGET_ICON_BASE64 } from '../assets/widgetIcon';
import { buildSettingsWindowLines } from './psSettingsWindow';

// 생성기 자체(이 파일)의 PowerShell/WPF 산출물이 바뀔 때마다 올려줌. configHash에 이 값을 섞어 넣어서,
// 스크립트 로직 자체가 바뀌면 예전에 컴파일해 둔 exe가 자동으로 "낡음" 판정을 받아 재컴파일되도록 함 —
// 이걸 빼먹으면 코드를 고쳐도 이미 설치된 사용자의 exe에는 영원히 반영되지 않는다.
// 주의: 사용자 설정(학교/테마/...)은 이제 config.json으로 분리되어 있어서 이 해시에 안 들어간다 —
// 설정 변경은 재컴파일 없이 즉시 반영되고(Rebuild-Widget), exe는 오직 "코드가 바뀐 경우"에만 다시 빌드하면 됨.
const GENERATOR_VERSION = '2026-09-02.2';

function hashConfig(obj: unknown): string {
  const str = JSON.stringify(obj);
  let h1 = 0xdeadbeef ^ str.length;
  let h2 = 0x41c6ce57 ^ str.length;
  for (let i = 0; i < str.length; i++) {
    const ch = str.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507) ^ Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507) ^ Math.imul(h1 ^ (h1 >>> 13), 3266489909);
  return (4294967296 * (2097151 & h2) + (h1 >>> 0)).toString(16);
}

export function generatePowerShellScript(config: WidgetConfig): string {
  const { todos } = config;
  const configHash = hashConfig({ v: GENERATOR_VERSION });

  // config.json 최초 시드값 — todos는 별도 파일(todos.json)로 이미 관리되므로 제외.
  // PS 단일따옴표 문자열 리터럴에 꽂으므로 내부의 ' 는 '' 로 두 번 반복해서 이스케이프.
  const { todos: _omitTodos, ...configWithoutTodos } = config;
  const seedConfigJson = JSON.stringify(configWithoutTodos).replace(/'/g, "''");
  const todosJson = JSON.stringify(todos).replace(/'/g, "''");

  // Build script using string array join to prevent template literal backtick collisions
  const lines: string[] = [
    '<#',
    '================================================================================',
    '  [NEWSchoolWidget (진화형) - 학교 생활 윈도우 위젯]',
    '  - 환경: Windows 10 / 11 PowerShell + WPF Native GUI',
    '  - 주요 기능:',
    '    1) 테두리 없는 깔끔한 모던 반투명 아크릴 위젯',
    '    2) 마우스 드래그 이동 & 손 떼면 모니터 상단(좌/우 선택 가능)으로 자동 스냅 (멀티 모니터 완벽 지원)',
    '    3) 실시간 날짜, 시계 및 시험/방학 D-Day 카운터',
    '    4) 요일별 교사/학생 시간표',
    '    5) 나이스(NEIS) 오픈 API 실시간 급식 (13:30 기준 오늘/내일 급식 자동 전환)',
    '    6) 할 일(TO-DO) 리스트 (추가/완료/삭제, 파일 자동 저장, 동적 높이 조절)',
    '    7) 위젯 안 "⚙ 설정" 창에서 학교/시간표/D-Day/테마/자동실행을 직접 편집 (재다운로드 불필요)',
    '================================================================================',
    '#>',
    '',
    '# 0. 전용 실행파일(.exe) 자동 준비',
    '#    - 이 스크립트가 컴파일된 고유 .exe로 다시 태어나면, 이후 실행부터는 그 exe로 바로 넘어가기',
    '#      때문에 작업표시줄/작업관리자에 "Windows PowerShell"이 아니라 전용 아이콘·이름으로 보이고',
    '#      콘솔/보안 경고도 거치지 않게 됨. 사용자 설정은 config.json에 따로 있어서 설정을 바꿔도',
    '#      이 exe를 다시 컴파일할 필요가 없음(아래 GENERATOR_VERSION이 바뀔 때만 재컴파일).',
    `$Global:ConfigHash = "${configHash}"`,
    '$Global:AppDir  = Join-Path $env:LOCALAPPDATA "NEWSchoolWidget-Evolved"',
    '$Global:AppExe  = Join-Path $Global:AppDir "NEWSchoolWidget-Evolved.exe"',
    '$Global:AppMeta = Join-Path $Global:AppDir "build-meta.json"',
    'if (-not (Test-Path $Global:AppDir)) { New-Item -ItemType Directory -Path $Global:AppDir -Force | Out-Null }',
    '# 예전 버전(공용 이름 NEWSchoolWidget)으로 등록됐던 시작프로그램 항목이 있으면 정리 (기본형/모바일형과 이름이 겹치던 구버전 잔재)',
    'try { Remove-ItemProperty -Path "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" -Name "NEWSchoolWidget" -ErrorAction SilentlyContinue } catch { }',
    '',
    '# 지금 이 코드를 실행 중인 게 이미 컴파일된 exe 자신인지 확인 (powershell.exe로 돌고 있으면 원본 상태)',
    'try {',
    '    $Global:RunningAsCompiledExe = ([System.Diagnostics.Process]::GetCurrentProcess().MainModule.FileName) -like "*NEWSchoolWidget-Evolved.exe"',
    '} catch { $Global:RunningAsCompiledExe = $false }',
    '',
    'if (-not $Global:RunningAsCompiledExe) {',
    '    # 0.1 이미 지금 코드 버전 그대로 컴파일된 exe가 있으면 PowerShell 대신 그쪽으로 바로 넘김',
    '    $existingMeta = $null',
    '    if (Test-Path $Global:AppMeta) {',
    '        try { $existingMeta = Get-Content $Global:AppMeta -Raw -Encoding UTF8 | ConvertFrom-Json } catch { }',
    '    }',
    '    if ((Test-Path $Global:AppExe) -and $existingMeta -and ($existingMeta.configHash -eq $Global:ConfigHash)) {',
    '        Start-Process -FilePath $Global:AppExe',
    '        Exit',
    '    }',
    '',
    '    # 0.2 콘솔 창 없이 조용히 재실행 (최초 1회만) - "PowerShell에서 실행"으로 띄워도 검은 창이 뜨지 않도록',
    '    if ($PSCommandPath -and ($env:SCHOOLWIDGET_EVOLVED_RELAUNCHED -ne "1")) {',
    '        $env:SCHOOLWIDGET_EVOLVED_RELAUNCHED = "1"',
    '        Start-Process powershell.exe -WindowStyle Hidden -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Sta -WindowStyle Hidden -File `"$PSCommandPath`""',
    '        Exit',
    '    }',
    '}',
    '',
    'try {',
    '    # 0.5 powershell.exe는 기본적으로 DPI-aware가 아니라서, Windows가 창 전체를 배율만큼',
    '    # 강제로 늘려 그려버려(DPI 가상화) 화면 크기 계산이 실제 모니터 기준과 어긋날 수 있음.',
    '    # 단, PowerShell 5.1이 사용하는 .NET Framework의 WPF는 Per-Monitor-V2(-4) DPI 인식을',
    '    # 온전히 지원하지 않아서(.NET Core/5+ WPF에서만 완전히 지원), -4로 설정하면 다른 배율의',
    '    # 모니터로 옮길 때 자동 재조정을 시도하다가 레이아웃이 깨짐. 대신 System-Aware(-2)를 써서',
    '    # "시작한 모니터 기준으로 고정, 모니터 이동 시 자동 재조정은 시도하지 않음" 방식으로 안전하게 처리',
    '    try {',
    '        Add-Type -Namespace SchoolWidgetEvolvedNative -Name DpiHelper -MemberDefinition @"',
    '[System.Runtime.InteropServices.DllImport("user32.dll")]',
    'public static extern bool SetProcessDpiAwarenessContext(IntPtr value);',
    '"@',
    '        [SchoolWidgetEvolvedNative.DpiHelper]::SetProcessDpiAwarenessContext([IntPtr](-2)) | Out-Null',
    '    } catch { }',
    '',
    '    # 1. 필수 .NET 어셈블리 로드',
    '    Add-Type -AssemblyName PresentationFramework',
    '    Add-Type -AssemblyName PresentationCore',
    '    Add-Type -AssemblyName WindowsBase',
    '    Add-Type -AssemblyName System.Windows.Forms',
    '    Add-Type -AssemblyName System.Drawing',
    '    Add-Type -AssemblyName System.Xml',
    '',
    '    # 1.5 백그라운드에서 전용 실행파일(.exe) 준비 (코드 버전이 그대로면 건너뜀). 이미 컴파일된',
    '    # exe로 실행 중일 때는 스스로를 또 컴파일할 필요가 없으므로 건너뜀. 위젯 UI는 이 작업을 기다리지 않음.',
    '    function Start-BackgroundCompile {',
    '        if (Test-Path $Global:AppExe) {',
    '            $meta = $null',
    '            if (Test-Path $Global:AppMeta) { try { $meta = Get-Content $Global:AppMeta -Raw -Encoding UTF8 | ConvertFrom-Json } catch { } }',
    '            if ($meta -and ($meta.configHash -eq $Global:ConfigHash)) { return }',
    '        }',
    '        if (-not $PSCommandPath) { return }',
    '        $srcPath  = $PSCommandPath',
    '        $exePath  = $Global:AppExe',
    '        $metaPath = $Global:AppMeta',
    `        $iconB64  = "${WIDGET_ICON_BASE64}"`,
    '        $hashVal  = $Global:ConfigHash',
    '        Start-Job -ScriptBlock {',
    '            param($srcPath, $exePath, $metaPath, $iconB64, $hashVal)',
    '            try {',
    '                if (-not (Get-Module -ListAvailable -Name ps2exe)) {',
    '                    # PSGallery가 기본적으로 Untrusted 상태라 Install-Module -Force만으로는',
    '                    # (특히 Windows PowerShell 5.1 번들 PowerShellGet에서) 확인 프롬프트를 완전히',
    '                    # 우회하지 못해 백그라운드(비대화형)에서는 조용히 실패할 수 있음 — 신뢰 등록과',
    '                    # NuGet 공급자 부트스트랩을 먼저 명시적으로 해 둠',
    '                    if (-not (Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue)) {',
    '                        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Scope CurrentUser -ErrorAction Stop | Out-Null',
    '                    }',
    '                    if ((Get-PSRepository -Name PSGallery -ErrorAction SilentlyContinue).InstallationPolicy -ne "Trusted") {',
    '                        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted -ErrorAction SilentlyContinue',
    '                    }',
    '                    Install-Module -Name ps2exe -Scope CurrentUser -Force -AllowClobber -SkipPublisherCheck -ErrorAction Stop',
    '                }',
    '                Import-Module ps2exe -ErrorAction Stop',
    '                $buildDir = Join-Path $env:TEMP "NEWSchoolWidgetEvolvedBuild"',
    '                New-Item -ItemType Directory -Path $buildDir -Force | Out-Null',
    '                $iconPath = Join-Path $buildDir "icon.ico"',
    '                [System.IO.File]::WriteAllBytes($iconPath, [Convert]::FromBase64String($iconB64))',
    '                $tmpExe = Join-Path $buildDir "NEWSchoolWidget-Evolved.exe"',
    '                Invoke-ps2exe -inputFile $srcPath -outputFile $tmpExe -iconFile $iconPath -noConsole -STA `',
    '                    -title "학교 생활 위젯 (진화형)" -product "NEWSchoolWidget-Evolved" -company "NEWSchoolWidget-Evolved" -version "1.0.0.0" -ErrorAction Stop',
    '                Copy-Item -Path $tmpExe -Destination $exePath -Force',
    '                @{ configHash = $hashVal; builtAt = (Get-Date).ToString("o") } | ConvertTo-Json | Set-Content -Path $metaPath -Encoding UTF8',
    '            } catch { }',
    '        } -ArgumentList $srcPath, $exePath, $metaPath, $iconB64, $hashVal | Out-Null',
    '    }',
    '',
    '    # 2. 설정/할일 파일 경로 및 최초 시드값 (내 문서\\NEWSchoolWidget\\config.json, todos.json)',
    '    $Global:ConfigDir  = [System.IO.Path]::Combine($env:USERPROFILE, "Documents", "NEWSchoolWidget")',
    '    $Global:ConfigFile = [System.IO.Path]::Combine($Global:ConfigDir, "config.json")',
    '    if (!(Test-Path $Global:ConfigDir)) { New-Item -ItemType Directory -Path $Global:ConfigDir -Force | Out-Null }',
    `    $Global:SeedConfigJson = '${seedConfigJson}'`,
    '',
    '    $Global:TodoDir  = [System.IO.Path]::Combine($env:USERPROFILE, "Documents", "NEWSchoolWidget")',
    '    $Global:TodoFile = [System.IO.Path]::Combine($Global:TodoDir, "todos.json")',
    '    if (!(Test-Path $Global:TodoDir)) { New-Item -ItemType Directory -Path $Global:TodoDir -Force | Out-Null }',
    `    $Global:InitialTodosJson = '${todosJson}'`,
    '    # 주의: @(...) 안에 파이프라인을 직접 넣으면 안 됨 - 빈 JSON 배열("[]")일 때',
    '    # ConvertFrom-Json이 "빈 배열 그 자체"를 파이프라인 출력 1개로 내보내서,',
    '    # @() 로 감싸면 [빈배열]이라는 1개짜리 중첩 배열이 되어버리는 PS 5.1 함정이 있음.',
    '    # 반드시 변수에 먼저 담은 뒤 @() 로 감싸야 빈 목록이 정상적으로 Count=0 이 됨.',
    '    $Global:InitialTodosRaw = $Global:InitialTodosJson | ConvertFrom-Json',
    '    $Global:InitialTodosData = @($Global:InitialTodosRaw)',
    '',
    '    $Global:CardOuterMargin = 10   # XAML의 Border Margin="10" (그림자 렌더링용 여백) 보정값',
    '    $Global:DragTodoId = $null     # 할 일 드래그 순서변경 중 잡고 있는 항목의 id',
    '',
    '    # 2.5 테마 → WPF ARGB 색상표. 웹 시뮬레이터(Widget.tsx)/ConfigPanel.tsx/types.ts와 함께',
    '    # .claude/skills/widget-theme-sync/SKILL.md 가 관리하는 색상 동기화 지점 중 하나 — 테마를',
    '    # 추가/수정할 때는 반드시 그 스킬 문서와 이 함수를 같이 확인할 것.',
    '    function Get-ThemeColors {',
    '        param([string]$ThemeId, [string]$CustomAccent)',
    '        $c = [ordered]@{',
    '            ContainerBg = "#E60F172A"; CardBg = "#B31E293B"; CardBorder = "#99334155"',
    '            TextPrimary = "#F1F5F9"; TextSecondary = "#94A3B8"',
    '            AccentColor = "#60A5FA"; AccentButtonColor = "#2563EB"; ButtonTextColor = "#FFFFFF"',
    '        }',
    '        switch ($ThemeId) {',
    '            "light-acrylic" {',
    '                $c.ContainerBg = "#F2FFFFFF"; $c.CardBg = "#E6F8FAFC"; $c.CardBorder = "#CCE2E8F0"',
    '                $c.TextPrimary = "#1E293B"; $c.TextSecondary = "#64748B"',
    '                $c.AccentColor = "#2563EB"; $c.AccentButtonColor = "#2563EB"',
    '            }',
    '            "emerald-glass" {',
    '                $c.ContainerBg = "#E6022C22"; $c.CardBg = "#99064E3B"; $c.CardBorder = "#80047857"',
    '                $c.TextPrimary = "#ECFDF5"; $c.TextSecondary = "#CC6EE7B7"',
    '                $c.AccentColor = "#34D399"; $c.AccentButtonColor = "#059669"',
    '            }',
    '            "indigo-glass" {',
    '                $c.ContainerBg = "#E61E1B4B"; $c.CardBg = "#99312E81"; $c.CardBorder = "#804338CA"',
    '                $c.TextPrimary = "#EEF2FF"; $c.TextSecondary = "#CCA5B4FC"',
    '                $c.AccentColor = "#818CF8"; $c.AccentButtonColor = "#4F46E5"',
    '            }',
    '            "slate-glass" {',
    '                $c.ContainerBg = "#D9334155"; $c.CardBg = "#99475569"; $c.CardBorder = "#8064748B"',
    '                $c.TextPrimary = "#F8FAFC"; $c.TextSecondary = "#CBD5E1"',
    '                $c.AccentColor = "#38BDF8"; $c.AccentButtonColor = "#0284C7"',
    '            }',
    '            "sakura-glass" {',
    '                $c.ContainerBg = "#E6500724"; $c.CardBg = "#99831843"; $c.CardBorder = "#80BE185D"',
    '                $c.TextPrimary = "#FDF2F8"; $c.TextSecondary = "#F9A8D4"',
    '                $c.AccentColor = "#F472B6"; $c.AccentButtonColor = "#DB2777"',
    '            }',
    '            "amber-glass" {',
    '                $c.ContainerBg = "#E6451A03"; $c.CardBg = "#9978350F"; $c.CardBorder = "#80B45309"',
    '                $c.TextPrimary = "#FFFBEB"; $c.TextSecondary = "#CCFCD34D"',
    '                $c.AccentColor = "#FBBF24"; $c.AccentButtonColor = "#D97706"',
    '            }',
    '            "mono-glass" {',
    '                $c.ContainerBg = "#F20A0A0A"; $c.CardBg = "#B3171717"; $c.CardBorder = "#99404040"',
    '                $c.TextPrimary = "#FAFAFA"; $c.TextSecondary = "#A3A3A3"',
    '                $c.AccentColor = "#FACC15"; $c.AccentButtonColor = "#EAB308"; $c.ButtonTextColor = "#000000"',
    '            }',
    '        }',
    '        if ($CustomAccent) {',
    '            $c.AccentColor = $CustomAccent',
    '            $c.AccentButtonColor = $CustomAccent',
    '            $c.ButtonTextColor = "#FFFFFF"',
    '        }',
    '        return $c',
    '    }',
    '',
    '    # 2.6 설정 로드/저장 — config.json이 있으면 그걸 우선, 없으면(최초 실행) 스튜디오가 구워둔',
    '    # 시드값으로 처음 만듦. 한 번 만들어지고 나면 그 다음부터는 웹에서 다시 받아도 로컬 설정이 우선.',
    '    function Load-Config {',
    '        if (Test-Path $Global:ConfigFile) {',
    '            try {',
    '                $json = Get-Content $Global:ConfigFile -Raw -Encoding UTF8',
    '                return ($json | ConvertFrom-Json)',
    '            } catch { }',
    '        }',
    '        $seed = $Global:SeedConfigJson | ConvertFrom-Json',
    '        Save-Config $seed',
    '        return $seed',
    '    }',
    '',
    '    function Save-Config {',
    '        param($cfg)',
    '        $json = $cfg | ConvertTo-Json -Depth 10',
    '        [System.IO.File]::WriteAllText($Global:ConfigFile, $json, [System.Text.Encoding]::UTF8)',
    '    }',
    '',
    '    # 2.7 로드된 설정을 나머지 함수들이 쓰는 $Global 변수들로 반영. 최초 실행과 설정 저장(Apply-NewConfig)',
    '    # 양쪽에서 똑같이 호출되므로, 여기 반영되는 값들은 항상 config.json과 일치한다.',
    '    function Sync-GlobalsFromConfig {',
    '        param($cfg)',
    '        $Global:Config = $cfg',
    '        $Global:OfficeCode = $cfg.school.officeCode',
    '        $Global:SchoolCode = $cfg.school.schoolCode',
    '        $Global:SchoolName = $cfg.school.schoolName',
    '        $Global:SnapSide = if ($cfg.snapSide -eq "left") { "Left" } else { "Right" }',
    '        $Global:SnapMargin = [double]$cfg.snapMargin',
    '        $Global:FontScale = if ($cfg.fontScale -and $cfg.fontScale -gt 0) { [double]$cfg.fontScale } else { 1.0 }',
    '        $Global:CornerRadius = if ($cfg.cornerRadius -and $cfg.cornerRadius -gt 0) { [double]$cfg.cornerRadius } else { 18 }',
    '        $Global:InnerRadius = [Math]::Max(6, [Math]::Round($Global:CornerRadius * 0.65))',
    '        $Global:Opacity = if ($cfg.opacity) { [double]$cfg.opacity } else { 1.0 }',
    '        $Global:AlwaysOnTop = [bool]$cfg.alwaysOnTop',
    '        $switchParts = @("$($cfg.mealSwitchTime)".Split(":"))',
    '        $Global:SwitchHour = 13',
    '        $Global:SwitchMinute = 30',
    '        if ($switchParts.Count -eq 2) {',
    '            $parsedH = 0; $parsedM = 0',
    '            if ([int]::TryParse($switchParts[0], [ref]$parsedH)) { $Global:SwitchHour = $parsedH }',
    '            if ([int]::TryParse($switchParts[1], [ref]$parsedM)) { $Global:SwitchMinute = $parsedM }',
    '        }',
    '        $Global:ShowAllergies = [bool]$cfg.showAllergies',
    '        $Global:ShowCalories = [bool]$cfg.showCalories',
    '        $Global:UserRoleText = if ($cfg.userRole -eq "teacher") { "교사용" } else { "학생용" }',
    '        $Global:AutoStartOnLogin = [bool]$cfg.autoStartOnLogin',
    '        $Global:TimetableData = @($cfg.timetable)',
    '        $Global:DDaysData = @($cfg.ddays)',
    '        $Global:Colors = Get-ThemeColors -ThemeId $cfg.theme -CustomAccent $cfg.customAccentColor',
    '    }',
    '',
    '    # 3. WPF XAML 정의 (테두리 없는 창, 반투명 효과, 자동 높이) — 실제 콘텐츠는 매번 현재',
    '    # $Global 설정값으로 새로 그려지므로, 설정을 바꾸면 창을 새로 안 띄우고도 즉시 반영 가능(Rebuild-Widget)',
    '    function Build-WidgetXaml {',
    '@"',
    '<Border xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" Margin="10" CornerRadius="$($Global:CornerRadius)" BorderThickness="1" BorderBrush="$($Global:Colors.CardBorder)" Background="$($Global:Colors.ContainerBg)" Opacity="$($Global:Opacity)">',
    '    <Border.LayoutTransform>',
    '        <ScaleTransform ScaleX="$($Global:FontScale)" ScaleY="$($Global:FontScale)"/>',
    '    </Border.LayoutTransform>',
    '    <Border.Effect>',
    '        <DropShadowEffect BlurRadius="18" ShadowDepth="4" Direction="270" Color="#000000" Opacity="0.45"/>',
    '    </Border.Effect>',
    '',
    '    <Grid Margin="16">',
    '        <Grid.RowDefinitions>',
    '            <RowDefinition Height="Auto"/>',
    '            <RowDefinition Height="Auto"/>',
    '            <RowDefinition Height="Auto"/>',
    '            <RowDefinition Height="Auto"/>',
    '            <RowDefinition Height="Auto"/>',
    '            <RowDefinition Height="Auto"/>',
    '        </Grid.RowDefinitions>',
    '',
    '        <!-- Row 0: Header (학교명, 날짜, 시계, 설정/새로고침/닫기 버튼) -->',
    '        <Grid Grid.Row="0" Margin="0,0,0,10">',
    '            <Grid.ColumnDefinitions>',
    '                <ColumnDefinition Width="*"/>',
    '                <ColumnDefinition Width="Auto"/>',
    '            </Grid.ColumnDefinitions>',
    '            <StackPanel Grid.Column="0">',
    '                <StackPanel Orientation="Horizontal" VerticalAlignment="Center">',
    '                    <Border CornerRadius="4" Background="#333B82F6" BorderBrush="#4D60A5FA" BorderThickness="1" Padding="5,1,5,1">',
    '                        <TextBlock x:Name="TxtSchoolName" Text="$($Global:SchoolName)" FontSize="10" FontWeight="Bold" Foreground="#60A5FA"/>',
    '                    </Border>',
    '                    <TextBlock x:Name="TxtUserRole" Text="$($Global:UserRoleText)" FontSize="10" Foreground="$($Global:Colors.TextSecondary)" Margin="6,0,0,0" VerticalAlignment="Center"/>',
    '                </StackPanel>',
    '                <TextBlock x:Name="TxtCurrentDate" Text="날짜 로딩 중..." FontSize="16" FontWeight="Bold" Foreground="$($Global:Colors.TextPrimary)" Margin="0,4,0,0"/>',
    '                <TextBlock x:Name="TxtCurrentTime" Text="00:00:00" FontSize="14" FontWeight="Medium" FontFamily="Consolas" Foreground="$($Global:Colors.TextSecondary)" Margin="0,2,0,0"/>',
    '            </StackPanel>',
    '            <StackPanel Grid.Column="1" Orientation="Horizontal" VerticalAlignment="Top">',
    '                <Button x:Name="BtnSettings" Content="⚙" Width="22" Height="22" Margin="0,0,4,0" Background="#33000000" Foreground="$($Global:Colors.TextSecondary)" BorderBrush="$($Global:Colors.CardBorder)" BorderThickness="1" Cursor="Hand" FontSize="12" ToolTip="설정"/>',
    '                <Button x:Name="BtnRefresh" Content="새로고침" Height="22" Padding="6,0" Margin="0,0,4,0" Background="#33000000" Foreground="$($Global:Colors.TextSecondary)" BorderBrush="$($Global:Colors.CardBorder)" BorderThickness="1" Cursor="Hand" FontSize="10" ToolTip="새로고침"/>',
    '                <Button x:Name="BtnClose" Content="✕" Width="22" Height="22" Background="#33000000" Foreground="$($Global:Colors.TextSecondary)" BorderBrush="$($Global:Colors.CardBorder)" BorderThickness="1" Cursor="Hand" FontSize="11" ToolTip="위젯 닫기"/>',
    '            </StackPanel>',
    '        </Grid>',
    '',
    '        <!-- Row 1: Divider (날짜/시간과 D-Day 사이 구분선) -->',
    '        <Rectangle Grid.Row="1" Height="1" Fill="$($Global:Colors.CardBorder)" Margin="0,0,0,10"/>',
    '',
    '        <!-- Row 2: D-Day Badges -->',
    '        <WrapPanel x:Name="PnlDDays" Grid.Row="2" Width="288" HorizontalAlignment="Left" Margin="0,0,0,10" />',
    '',
    '        <!-- Row 3: Timetable Section -->',
    '        <Border Grid.Row="3" Background="$($Global:Colors.CardBg)" BorderBrush="$($Global:Colors.CardBorder)" BorderThickness="1" CornerRadius="$($Global:InnerRadius)" Padding="10" Margin="0,0,0,10">',
    '            <StackPanel>',
    '                <Grid Margin="0,0,0,8">',
    '                    <StackPanel Orientation="Horizontal">',
    '                        <ContentControl x:Name="IconClock" VerticalAlignment="Center" Margin="0,0,4,0" Focusable="False"/>',
    '                        <TextBlock Text="시간표" FontSize="12" FontWeight="Bold" Foreground="$($Global:Colors.TextPrimary)"/>',
    '                    </StackPanel>',
    '                    <Border HorizontalAlignment="Right" CornerRadius="6" Background="#33000000" BorderBrush="#0DFFFFFF" BorderThickness="1" Padding="2">',
    '                        <StackPanel x:Name="PnlDaySelector" Orientation="Horizontal"/>',
    '                    </Border>',
    '                </Grid>',
    '                <StackPanel x:Name="PnlTimetable" Margin="0,0,0,0"/>',
    '            </StackPanel>',
    '        </Border>',
    '',
    '        <!-- Row 4: NEIS Meal Section -->',
    '        <Border Grid.Row="4" Background="$($Global:Colors.CardBg)" BorderBrush="$($Global:Colors.CardBorder)" BorderThickness="1" CornerRadius="$($Global:InnerRadius)" Padding="10" Margin="0,0,0,10">',
    '            <StackPanel>',
    '                <Grid Margin="0,0,0,6">',
    '                    <StackPanel Orientation="Horizontal">',
    '                        <ContentControl x:Name="IconMeal" VerticalAlignment="Center" Margin="0,0,4,0" Focusable="False"/>',
    '                        <TextBlock x:Name="TxtMealTitle" Text="오늘의 급식" FontSize="12" FontWeight="Bold" Foreground="$($Global:Colors.TextPrimary)"/>',
    '                        <Border CornerRadius="4" Background="#3310B981" BorderBrush="#4D34D399" BorderThickness="1" Padding="5,1,5,1" Margin="5,0,0,0">',
    '                            <TextBlock x:Name="TxtMealDateBadge" Text="급식 정보" FontSize="10" Foreground="#34D399"/>',
    '                        </Border>',
    '                    </StackPanel>',
    '                    <TextBlock x:Name="TxtMealSwitchLabel" Text="$($Global:Config.mealSwitchTime) 전환" HorizontalAlignment="Right" FontSize="9" Foreground="$($Global:Colors.TextSecondary)"/>',
    '                </Grid>',
    '                <TextBlock x:Name="TxtMealLoading" Text="급식 정보를 불러오는 중입니다..." TextWrapping="Wrap" FontSize="12" Foreground="$($Global:Colors.TextPrimary)"/>',
    '                <UniformGrid x:Name="PnlMealMenu" Columns="2" />',
    '                <Grid Margin="0,4,0,0">',
    '                    <TextBlock x:Name="TxtMealCalories" Text="" FontSize="10" Foreground="$($Global:Colors.TextSecondary)"/>',
    '                    <TextBlock x:Name="TxtMealApiCredit" Text="나이스 Open API 연동" HorizontalAlignment="Right" FontSize="9" Foreground="$($Global:Colors.TextSecondary)" Opacity="0.8"/>',
    '                </Grid>',
    '            </StackPanel>',
    '        </Border>',
    '',
    '        <!-- Row 5: To-Do Section (동적 크기 조절) -->',
    '        <Border Grid.Row="5" Background="$($Global:Colors.CardBg)" BorderBrush="$($Global:Colors.CardBorder)" BorderThickness="1" CornerRadius="$($Global:InnerRadius)" Padding="10" Margin="0,0,0,0">',
    '            <StackPanel>',
    '                <Grid Margin="0,0,0,6">',
    '                    <StackPanel Orientation="Horizontal">',
    '                        <ContentControl x:Name="IconTodo" VerticalAlignment="Center" Margin="0,0,4,0" Focusable="False"/>',
    '                        <TextBlock Text="할 일 목록 (TO-DO)" FontSize="12" FontWeight="Bold" Foreground="$($Global:Colors.TextPrimary)"/>',
    '                    </StackPanel>',
    '                    <TextBlock x:Name="TxtTodoCount" Text="0개 남음" HorizontalAlignment="Right" FontSize="10" Foreground="$($Global:Colors.TextSecondary)"/>',
    '                </Grid>',
    '',
    '                <!-- Todo Input Box -->',
    '                <Grid Margin="0,0,0,8">',
    '                    <Grid.ColumnDefinitions>',
    '                        <ColumnDefinition Width="*"/>',
    '                        <ColumnDefinition Width="Auto"/>',
    '                    </Grid.ColumnDefinitions>',
    '                    <TextBox x:Name="TxtNewTodo" Grid.Column="0" Height="26" Background="#22000000" Foreground="$($Global:Colors.TextPrimary)" BorderBrush="$($Global:Colors.CardBorder)" BorderThickness="1" Padding="6,3" VerticalContentAlignment="Center" FontSize="12"/>',
    '                    <Button x:Name="BtnAddTodo" Grid.Column="1" Content="추가" Width="44" Height="26" Margin="4,0,0,0" Background="$($Global:Colors.AccentButtonColor)" Foreground="$($Global:Colors.ButtonTextColor)" FontWeight="Bold" BorderThickness="0" Cursor="Hand" FontSize="11"/>',
    '                </Grid>',
    '',
    '                <!-- Dynamic Items List (시뮬레이터의 max-h-48 overflow-y-auto와 동일하게 -->',
    '                <!-- 목록 안에서만 스크롤되어, 위젯 전체가 모니터 밖으로 무한정 길어지지 않음) -->',
    '                <ScrollViewer x:Name="SvTodoList" VerticalScrollBarVisibility="Auto" HorizontalScrollBarVisibility="Disabled">',
    '                    <StackPanel x:Name="PnlTodoList" />',
    '                </ScrollViewer>',
    '            </StackPanel>',
    '        </Border>',
    '',
    '    </Grid>',
    '</Border>',
    '"@',
    '    }',
    '',
    '    # 4. UI 컨트롤 바인딩 + 자식 컨트롤 이벤트 연결 — Content를 새로 그릴 때마다(Rebuild-Widget) 다시 호출됨',
    '    function Bind-WidgetControls {',
    '        $Global:TxtSchoolName    = $Global:Window.Content.FindName("TxtSchoolName")',
    '        $Global:TxtCurrentDate   = $Global:Window.Content.FindName("TxtCurrentDate")',
    '        $Global:TxtCurrentTime   = $Global:Window.Content.FindName("TxtCurrentTime")',
    '        $Global:PnlDDays         = $Global:Window.Content.FindName("PnlDDays")',
    '        $Global:PnlDaySelector   = $Global:Window.Content.FindName("PnlDaySelector")',
    '        $Global:PnlTimetable     = $Global:Window.Content.FindName("PnlTimetable")',
    '        $Global:IconClock        = $Global:Window.Content.FindName("IconClock")',
    '        $Global:IconMeal         = $Global:Window.Content.FindName("IconMeal")',
    '        $Global:IconTodo         = $Global:Window.Content.FindName("IconTodo")',
    '        $Global:TxtMealTitle     = $Global:Window.Content.FindName("TxtMealTitle")',
    '        $Global:TxtMealDateBadge = $Global:Window.Content.FindName("TxtMealDateBadge")',
    '        $Global:TxtMealSwitchLabel = $Global:Window.Content.FindName("TxtMealSwitchLabel")',
    '        $Global:TxtMealLoading   = $Global:Window.Content.FindName("TxtMealLoading")',
    '        $Global:PnlMealMenu      = $Global:Window.Content.FindName("PnlMealMenu")',
    '        $Global:TxtMealCalories  = $Global:Window.Content.FindName("TxtMealCalories")',
    '        $Global:TxtMealApiCredit = $Global:Window.Content.FindName("TxtMealApiCredit")',
    '        $Global:TxtTodoCount     = $Global:Window.Content.FindName("TxtTodoCount")',
    '        $Global:TxtNewTodo       = $Global:Window.Content.FindName("TxtNewTodo")',
    '        $Global:BtnAddTodo       = $Global:Window.Content.FindName("BtnAddTodo")',
    '        $Global:PnlTodoList      = $Global:Window.Content.FindName("PnlTodoList")',
    '        $Global:SvTodoList       = $Global:Window.Content.FindName("SvTodoList")',
    '        $Global:BtnClose         = $Global:Window.Content.FindName("BtnClose")',
    '        $Global:BtnRefresh       = $Global:Window.Content.FindName("BtnRefresh")',
    '        $Global:BtnSettings      = $Global:Window.Content.FindName("BtnSettings")',
    '',
    '        $Global:BtnClose.Add_Click({ $Global:Window.Close() })',
    '        $Global:BtnRefresh.Add_Click({ Update-AllData })',
    '        $Global:BtnAddTodo.Add_Click({ Add-NewTodo })',
    '        $Global:TxtNewTodo.Add_KeyDown({',
    '            param($s, $e)',
    '            if ($e.Key -eq [System.Windows.Input.Key]::Enter) { Add-NewTodo }',
    '        })',
    '        $Global:BtnSettings.Add_Click({ Show-SettingsWindow })',
    '    }',
    '',
    '    # 4.5 벡터 아이콘 렌더링 (GDI+ 컬러 이모지 한계 우회)',
    '    # GDI+(System.Drawing.Graphics)와 WPF의 기본 텍스트 렌더링 엔진은 둘 다 Windows 컬러',
    '    # 이모지 폰트의 COLR/CPAL 레이어를 합성하지 못해서, 이모지가 흑백 윤곽선 글꼴로만',
    '    # 추출되고 그 위에 브러시(색)를 칠하는 방식이 되어버림 - 그래서 어떤 브러시를 쓰든',
    '    # 결국 "흑백 윤곽선 하나"만 그려지는 것. 폰트/OS 컬러 레이어에 의존하지 않도록,',
    '    # 처음부터 색이 정해진 벡터 경로(Geometry)를 직접 그리면 항상 원하는 색으로 선명하게 나옴',
    '    function New-VectorIcon {',
    '        param([string]$Type, [string]$ColorHex = "#60A5FA", [double]$Size = 15)',
    '        $path = New-Object System.Windows.Shapes.Path',
    '        $path.Width = $Size',
    '        $path.Height = $Size',
    '        $path.Stretch = [System.Windows.Media.Stretch]::Uniform',
    '        $path.Fill = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($ColorHex)',
    '',
    '        if ($Type -eq "Clock") {',
    '            $path.Data = [System.Windows.Media.Geometry]::Parse("M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4M12.5,7V12.25L16.2,14.4L15.4,15.7L11,13V7H12.5Z")',
    '        } elseif ($Type -eq "Meal") {',
    '            $path.Data = [System.Windows.Media.Geometry]::Parse("M8,2A2,2 0 0,0 6,4V6H4A2,2 0 0,0 2,8V18A2,2 0 0,0 4,20H20A2,2 0 0,0 22,18V8A2,2 0 0,0 20,6H18V4A2,2 0 0,0 16,2H8M8,4H16V6H8V4M4,8H20V18H4V8Z")',
    '        } elseif ($Type -eq "Check") {',
    '            $path.Data = [System.Windows.Media.Geometry]::Parse("M19,3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3M10,17L5,12L6.41,10.59L10,14.17L17.59,6.58L19,8L10,17Z")',
    '        }',
    '        return $path',
    '    }',
    '',
    '    function Render-Icons {',
    '        if ($Global:IconClock) { $Global:IconClock.Content = New-VectorIcon -Type "Clock" -ColorHex "#60A5FA" -Size 14 }',
    '        if ($Global:IconMeal)  { $Global:IconMeal.Content  = New-VectorIcon -Type "Meal"  -ColorHex "#34D399" -Size 14 }',
    '        if ($Global:IconTodo)  { $Global:IconTodo.Content  = New-VectorIcon -Type "Check" -ColorHex "#FBBF24" -Size 14 }',
    '    }',
    '',
    '    # 5. 마우스 드래그 & 모니터 자동 스냅 (좌/우 선택 가능, 멀티 모니터 완벽 지원)',
    '    $Global:IsDragging = $false',
    '',
    '    function Snap-ToRightTop {',
    '        try {',
    '            $cursorPos = [System.Windows.Forms.Cursor]::Position',
    '            $screen = [System.Windows.Forms.Screen]::FromPoint($cursorPos)',
    '            $workArea = $screen.WorkingArea',
    '',
    '            $source = [System.Windows.PresentationSource]::FromVisual($Global:Window)',
    '            $dpiX = 1.0',
    '            $dpiY = 1.0',
    '            if ($source -and $source.CompositionTarget) {',
    '                $dpiX = $source.CompositionTarget.TransformToDevice.M11',
    '                $dpiY = $source.CompositionTarget.TransformToDevice.M22',
    '            }',
    '            if ($dpiX -le 0) { $dpiX = 1.0 }',
    '            if ($dpiY -le 0) { $dpiY = 1.0 }',
    '',
    '            $winWidth = [Math]::Round(340 * $Global:FontScale)',
    '            if ($Global:Window.ActualWidth -gt 50) { $winWidth = $Global:Window.ActualWidth }',
    '            # 창 안쪽 Border의 Margin="10"만큼 보정해서 실제 카드가 화면 가장자리에서',
    '            # 정확히 SnapMargin 만큼만 떨어지도록 함 (여백이 배로 생기는 문제 방지)',
    '            if ($Global:SnapSide -eq "Left") {',
    '                $targetLeft = ($workArea.Left / $dpiX) + $Global:SnapMargin - $Global:CardOuterMargin',
    '            } else {',
    '                $targetLeft = ($workArea.Right / $dpiX) - $winWidth - $Global:SnapMargin + $Global:CardOuterMargin',
    '            }',
    '            $targetTop  = ($workArea.Top / $dpiY) + $Global:SnapMargin - $Global:CardOuterMargin',
    '',
    '            $Global:Window.Left = $targetLeft',
    '            $Global:Window.Top  = $targetTop',
    '',
    '            # 안전장치: 할 일이 아무리 많이 쌓여도 위젯이 현재 모니터 높이를 넘지 않도록',
    '            # 창 자체에 MaxHeight를 강제로 걸어둠 (ScrollViewer만으로는 반복 갱신 시 완전히',
    '            # 신뢰할 수 없어서, 모니터 작업영역 높이 기준의 하드 캡을 이중으로 둠)',
    '            $Global:Window.MaxHeight = ($workArea.Height / $dpiY) - (2 * $Global:SnapMargin) - 20',
    '            # 더 크고 긴 모니터로 옮기면 할 일 목록도 남는 공간만큼 자동으로 같이 커지도록,',
    '            # 지금 이 모니터 기준으로 다시 계산해서 즉시 반영',
    '            Update-TodoScrollCap',
    '        } catch {',
    '            $winWidth = [Math]::Round(340 * $Global:FontScale)',
    '            if ($Global:Window.ActualWidth -gt 50) { $winWidth = $Global:Window.ActualWidth }',
    '            if ($Global:SnapSide -eq "Left") {',
    '                $Global:Window.Left = [System.Windows.SystemParameters]::WorkArea.Left + $Global:SnapMargin - $Global:CardOuterMargin',
    '            } else {',
    '                $Global:Window.Left = [System.Windows.SystemParameters]::WorkArea.Right - $winWidth - $Global:SnapMargin + $Global:CardOuterMargin',
    '            }',
    '            $Global:Window.Top  = [System.Windows.SystemParameters]::WorkArea.Top + $Global:SnapMargin - $Global:CardOuterMargin',
    '            $Global:Window.MaxHeight = [System.Windows.SystemParameters]::WorkArea.Height - (2 * $Global:SnapMargin) - 20',
    '            Update-TodoScrollCap',
    '        }',
    '    }',
    '',
    '    # 5.5 할 일 목록이 남는 공간을 끝까지 다 쓰도록, 실제 필요한 높이를 직접 측정해서',
    '    # 정확하게 계산하는 함수 (오전/오후 시간표 행 수, D-Day 배지 줄바꿈, 급식 메뉴 길이 등',
    '    # 콘텐츠에 따라 매번 다르기 때문에 고정값 추정 대신 실측이 필요함)',
    '    function Update-TodoScrollCap {',
    '        if (-not $Global:SvTodoList) { return }',
    '        try {',
    '            $cappedMaxHeight = $Global:Window.MaxHeight',
    '            # Window.MaxHeight가 걸려있으면 ActualHeight 자체가 이미 그 값으로 잘려서 나오기',
    '            # 때문에, "내용이 실제로 얼마나 필요로 하는지"를 재려면 상한을 잠깐 풀어야 함',
    '            $Global:Window.ClearValue([System.Windows.Window]::MaxHeightProperty)',
    '            $Global:SvTodoList.ClearValue([System.Windows.Controls.ScrollViewer]::HeightProperty)',
    '            $Global:Window.UpdateLayout()',
    '            $naturalHeight = $Global:Window.ActualHeight',
    '',
    '            # 상한을 다시 복원',
    '            $Global:Window.MaxHeight = $cappedMaxHeight',
    '',
    '            if ($cappedMaxHeight -and $naturalHeight -gt $cappedMaxHeight) {',
    '                # 넘치는 만큼만 정확히 할 일 목록에서 줄여서, 나머지 섹션은 항상 원래',
    '                # 크기 그대로 유지하고 남는 공간은 전부 할 일 목록이 쓰도록 함.',
    '                # Window.ActualHeight/MaxHeight는 LayoutTransform이 적용된 물리 픽셀 단위인 반면,',
    '                # SvTodoList.ActualHeight/Height는 변환 전(로컬) 단위라서 FontScale로 나눠서 맞춰줌',
    '                $overflowLocal = ($naturalHeight - $cappedMaxHeight) / $Global:FontScale',
    '                $currentSvHeight = $Global:SvTodoList.ActualHeight',
    '                $targetSvHeight = [Math]::Max(60, $currentSvHeight - $overflowLocal)',
    '                $Global:SvTodoList.Height = $targetSvHeight',
    '                $Global:Window.UpdateLayout()',
    '            }',
    '        } catch { }',
    '    }',
    '',
    '    # 5.6 자동 시작 설정 동기화 (컴퓨터 시작 시 자동 실행 체크박스)',
    '    # HKCU 아래라서 관리자 권한 불필요. exe가 아직 컴파일 전이어도 경로만 미리 등록해 두고,',
    '    # 다음 로그인 즈음엔 exe가 준비돼 있는 게 보통이라 문제 없음.',
    '    function Sync-AutoStart {',
    '        try {',
    '            $runKey = "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"',
    '            if ($Global:AutoStartOnLogin) {',
    '                Set-ItemProperty -Path $runKey -Name "NEWSchoolWidget-Evolved" -Value "`"$($Global:AppExe)`"" -Force',
    '            } else {',
    '                if (Get-ItemProperty -Path $runKey -Name "NEWSchoolWidget-Evolved" -ErrorAction SilentlyContinue) {',
    '                    Remove-ItemProperty -Path $runKey -Name "NEWSchoolWidget-Evolved" -ErrorAction SilentlyContinue',
    '                }',
    '            }',
    '        } catch { }',
    '    }',
    '',
    '    # 6. D-Day 렌더링 함수',
    '    function Update-DDays {',
    '        $Global:PnlDDays.Children.Clear()',
    '        $today = [DateTime]::Today',
    '',
    '        foreach ($item in $Global:DDaysData) {',
    '            try {',
    '                $target = [DateTime]::Parse($item.targetDate)',
    '                $diff = ($target - $today).Days',
    '                $ddayText = ""',
    '                # 시뮬레이터(SchoolWidgetCard.tsx)의 배지 색상과 동일: 기본(7일 초과 남음)은 파란색,',
    '                # 7일 이하 남음은 주황색, D-DAY는 빨강, 지난 일정은 회색',
    '                $borderColor = "#3B82F6"',
    '                $textColor   = "#93C5FD"',
    '',
    '                if ($diff -eq 0) {',
    '                    $ddayText = "D-DAY"',
    '                    $borderColor = "#EF4444"',
    '                    $textColor   = "#FCA5A5"',
    '                } elseif ($diff -gt 0) {',
    '                    $ddayText = "D-$diff"',
    '                    if ($diff -le 7) {',
    '                        $borderColor = "#F59E0B"',
    '                        $textColor   = "#FCD34D"',
    '                    }',
    '                } else {',
    '                    $ddayText = "D+$([Math]::Abs($diff))"',
    '                    $borderColor = "#475569"',
    '                    $textColor   = "#94A3B8"',
    '                }',
    '',
    '                $badge = New-Object System.Windows.Controls.Border',
    '                $badge.CornerRadius = [System.Windows.CornerRadius]6',
    '                # 상태 색상을 반투명 배경으로도 반영 (시뮬레이터의 bg-{color}/20 배지와 동일한 톤)',
    '                $badgeBgTint = "#33" + $borderColor.Substring(1)',
    '                $badge.Background = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($badgeBgTint)',
    '                $badge.BorderBrush = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($borderColor)',
    '                $badge.BorderThickness = [System.Windows.Thickness]1',
    '                $badge.Padding = [System.Windows.Thickness](New-Object System.Windows.Thickness(8, 2, 8, 2))',
    '                $badge.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(0, 0, 6, 4))',
    '',
    '                $sp = New-Object System.Windows.Controls.StackPanel',
    '                $sp.Orientation = [System.Windows.Controls.Orientation]::Horizontal',
    '',
    '                $title = New-Object System.Windows.Controls.TextBlock',
    '                $title.Text = "$($item.title) "',
    '                $title.FontSize = 11',
    '                $title.Opacity = 0.9',
    '                $title.TextWrapping = [System.Windows.TextWrapping]::Wrap',
    '                $title.MaxWidth = 160',
    '                $title.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($textColor)',
    '',
    '                $val = New-Object System.Windows.Controls.TextBlock',
    '                $val.Text = $ddayText',
    '                $val.FontSize = 11',
    '                $val.FontWeight = [System.Windows.FontWeights]::Bold',
    '                $val.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($textColor)',
    '',
    '                $sp.Children.Add($title) | Out-Null',
    '                $sp.Children.Add($val) | Out-Null',
    '                $badge.Child = $sp',
    '',
    '                $Global:PnlDDays.Children.Add($badge) | Out-Null',
    '            } catch { }',
    '        }',
    '    }',
    '',
    '    # 7. 요일 선택 pill 초기화 (시뮬레이터처럼 월~금 모두 클릭해서 확인 가능)',
    '    $Global:DaysKorean5 = @("월", "화", "수", "목", "금")',
    '    $Global:SelectedDay = "월"',
    '',
    '    function Refresh-DaySelectorHighlight {',
    '        foreach ($btn in $Global:PnlDaySelector.Children) {',
    '            if ($btn.Tag -eq $Global:SelectedDay) {',
    '                $btn.Background = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:Colors.AccentButtonColor)',
    '                $btn.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:Colors.ButtonTextColor)',
    '            } else {',
    '                $btn.Background = [System.Windows.Media.Brushes]::Transparent',
    '                $btn.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:Colors.TextSecondary)',
    '            }',
    '        }',
    '    }',
    '',
    '    function Init-DaySelector {',
    '        $Global:PnlDaySelector.Children.Clear()',
    '        $pillTemplate = [System.Windows.Markup.XamlReader]::Parse(@"',
    '<ControlTemplate xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" TargetType="Button">',
    '    <Border CornerRadius="4" Background="{TemplateBinding Background}" Padding="2">',
    '        <ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center"/>',
    '    </Border>',
    '</ControlTemplate>',
    '"@)',
    '        foreach ($d in $Global:DaysKorean5) {',
    '            $btn = New-Object System.Windows.Controls.Button',
    '            $btn.Content = $d',
    '            $btn.Tag = $d',
    '            $btn.Width = 22',
    '            $btn.Height = 20',
    '            $btn.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(1, 0, 1, 0))',
    '            $btn.FontSize = 10',
    '            $btn.FontWeight = [System.Windows.FontWeights]::SemiBold',
    '            $btn.BorderThickness = [System.Windows.Thickness]0',
    '            $btn.Template = $pillTemplate',
    '            $btn.Cursor = [System.Windows.Input.Cursors]::Hand',
    '            $btn.Add_Click({',
    '                param($s, $e)',
    '                $Global:SelectedDay = $s.Tag',
    '                Refresh-DaySelectorHighlight',
    '                Update-Timetable',
    '            })',
    '            $Global:PnlDaySelector.Children.Add($btn) | Out-Null',
    '        }',
    '        Refresh-DaySelectorHighlight',
    '    }',
    '',
    '    # 8. 시간표 렌더링 함수 (1-4교시 / 5-7교시 2열 배치, 오전/오후 라벨, 선택한 요일 표시)',
    '    function Update-Timetable {',
    '        $Global:PnlTimetable.Children.Clear()',
    '        $now = Get-Date',
    '        $dayOfWeekIndex = [int]$now.DayOfWeek',
    '        $daysKorean = @("일", "월", "화", "수", "목", "금", "토")',
    '        $todayDayName = $daysKorean[$dayOfWeekIndex]',
    '',
    '        $targetDay = $Global:SelectedDay',
    '        $schedule = $Global:TimetableData | Where-Object { $_.day -eq $targetDay }',
    '        $isViewingToday = ($targetDay -eq $todayDayName)',
    '',
    '        if ($schedule -and $schedule.periods) {',
    '            # 2열 메인 그리드 생성',
    '            $grid = New-Object System.Windows.Controls.Grid',
    '            $col1 = New-Object System.Windows.Controls.ColumnDefinition',
    '            $col1.Width = [System.Windows.GridLength](New-Object System.Windows.GridLength(1, [System.Windows.GridUnitType]::Star))',
    '            $col2 = New-Object System.Windows.Controls.ColumnDefinition',
    '            $col2.Width = [System.Windows.GridLength](New-Object System.Windows.GridLength(1, [System.Windows.GridUnitType]::Star))',
    '            $grid.ColumnDefinitions.Add($col1)',
    '            $grid.ColumnDefinitions.Add($col2)',
    '',
    '            # 좌측 패널: 1~4교시 (오전)',
    '            $pnlLeft = New-Object System.Windows.Controls.StackPanel',
    '            $pnlLeft.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(0, 0, 4, 0))',
    '            [System.Windows.Controls.Grid]::SetColumn($pnlLeft, 0)',
    '            $hdrLeft = New-Object System.Windows.Controls.TextBlock',
    '            $hdrLeft.Text = "오전 (1~4교시)"',
    '            $hdrLeft.FontSize = 10',
    '            $hdrLeft.FontWeight = [System.Windows.FontWeights]::SemiBold',
    '            $hdrLeft.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:Colors.TextSecondary)',
    '            $hdrLeft.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(1, 0, 0, 2))',
    '            $pnlLeft.Children.Add($hdrLeft) | Out-Null',
    '',
    '            # 우측 패널: 5~7교시 (오후)',
    '            $pnlRight = New-Object System.Windows.Controls.StackPanel',
    '            $pnlRight.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(4, 0, 0, 0))',
    '            [System.Windows.Controls.Grid]::SetColumn($pnlRight, 1)',
    '            $hdrRight = New-Object System.Windows.Controls.TextBlock',
    '            $hdrRight.Text = "오후 (5~7교시)"',
    '            $hdrRight.FontSize = 10',
    '            $hdrRight.FontWeight = [System.Windows.FontWeights]::SemiBold',
    '            $hdrRight.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:Colors.TextSecondary)',
    '            $hdrRight.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(1, 0, 0, 2))',
    '            $pnlRight.Children.Add($hdrRight) | Out-Null',
    '',
    '            $periods = $schedule.periods',
    '            for ($i = 0; $i -lt $periods.Count; $i++) {',
    '                $periodNum = $i + 1',
    '                $subject = "-"',
    '                if ($periods[$i]) { $subject = $periods[$i] }',
    '',
    '                $itemBorder = New-Object System.Windows.Controls.Border',
    '                $itemBorder.CornerRadius = [System.Windows.CornerRadius]6',
    '                # 오늘 보고 있을 때만 시뮬레이터처럼 오전(파랑)/오후(초록) 톤으로 강조',
    '                if ($isViewingToday) {',
    '                    $tintColor = if ($periodNum -le 4) { "#1A60A5FA" } else { "#1A34D399" }',
    '                    $itemBorder.Background = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($tintColor)',
    '                } else {',
    '                    $itemBorder.Background = (New-Object System.Windows.Media.BrushConverter).ConvertFromString("#0DFFFFFF")',
    '                }',
    '                $itemBorder.BorderBrush = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:Colors.CardBorder)',
    '                $itemBorder.BorderThickness = [System.Windows.Thickness]1',
    '                $itemBorder.Padding = [System.Windows.Thickness](New-Object System.Windows.Thickness(5, 3, 5, 3))',
    '                $itemBorder.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(0, 1, 0, 2))',
    '',
    '                $itemGrid = New-Object System.Windows.Controls.Grid',
    '                $cNum = New-Object System.Windows.Controls.ColumnDefinition',
    '                $cNum.Width = [System.Windows.GridLength]::Auto',
    '                $cSub = New-Object System.Windows.Controls.ColumnDefinition',
    '                $cSub.Width = [System.Windows.GridLength](New-Object System.Windows.GridLength(1, [System.Windows.GridUnitType]::Star))',
    '                $itemGrid.ColumnDefinitions.Add($cNum)',
    '                $itemGrid.ColumnDefinitions.Add($cSub)',
    '',
    '                # 시뮬레이터처럼 오전/오후 색상은 테마와 무관하게 항상 blue-400 / emerald-400 고정',
    '                $periodColor = if ($periodNum -le 4) { "#60A5FA" } else { "#34D399" }',
    '                $txtNum = New-Object System.Windows.Controls.TextBlock',
    '                $txtNum.Text = "$($periodNum)교시 "',
    '                $txtNum.FontSize = 10',
    '                $txtNum.FontWeight = [System.Windows.FontWeights]::SemiBold',
    '                $txtNum.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($periodColor)',
    '                [System.Windows.Controls.Grid]::SetColumn($txtNum, 0)',
    '',
    '                $txtSub = New-Object System.Windows.Controls.TextBlock',
    '                $txtSub.Text = $subject',
    '                $txtSub.FontSize = 11',
    '                $txtSub.FontWeight = [System.Windows.FontWeights]::SemiBold',
    '                $txtSub.TextAlignment = [System.Windows.TextAlignment]::Right',
    '                $txtSub.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:Colors.TextPrimary)',
    '                [System.Windows.Controls.Grid]::SetColumn($txtSub, 1)',
    '',
    '                $itemGrid.Children.Add($txtNum) | Out-Null',
    '                $itemGrid.Children.Add($txtSub) | Out-Null',
    '                $itemBorder.Child = $itemGrid',
    '',
    '                if ($periodNum -le 4) {',
    '                    $pnlLeft.Children.Add($itemBorder) | Out-Null',
    '                } else {',
    '                    $pnlRight.Children.Add($itemBorder) | Out-Null',
    '                }',
    '            }',
    '',
    '            $grid.Children.Add($pnlLeft) | Out-Null',
    '            $grid.Children.Add($pnlRight) | Out-Null',
    '            $Global:PnlTimetable.Children.Add($grid) | Out-Null',
    '        }',
    '    }',
    '',
    '    # 8.5 급식 메뉴 불릿 2열 렌더링 (시뮬레이터 미리보기와 동일한 구성)',
    '    function Render-MealMenu {',
    '        param($items, [bool]$isFallback = $false)',
    '        $Global:TxtMealLoading.Visibility = [System.Windows.Visibility]::Collapsed',
    '        $Global:PnlMealMenu.Children.Clear()',
    '        $Global:PnlMealMenu.Columns = if ($isFallback) { 1 } else { 2 }',
    '',
    '        foreach ($dish in $items) {',
    '            $row = New-Object System.Windows.Controls.StackPanel',
    '            $row.Orientation = [System.Windows.Controls.Orientation]::Horizontal',
    '            $row.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(0, 0, 4, 3))',
    '',
    '            $bullet = New-Object System.Windows.Controls.TextBlock',
    '            $bullet.Text = "• "',
    '            $bullet.FontSize = 11',
    '            $bullet.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString("#34D399")',
    '',
    '            $txt = New-Object System.Windows.Controls.TextBlock',
    '            $txt.Text = $dish',
    '            $txt.FontSize = 11',
    '            $txt.TextWrapping = [System.Windows.TextWrapping]::Wrap',
    '            $txt.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:Colors.TextPrimary)',
    '',
    '            $row.Children.Add($bullet) | Out-Null',
    '            $row.Children.Add($txt) | Out-Null',
    '            $Global:PnlMealMenu.Children.Add($row) | Out-Null',
    '        }',
    '    }',
    '',
    '    # 9. 나이스(NEIS) 급식 API 호출 (13:30 기준 자동 전환)',
    '    function Update-MealInfo {',
    '        $now = Get-Date',
    '        $currentMins = ($now.Hour * 60) + $now.Minute',
    '        $switchMins  = ($Global:SwitchHour * 60) + $Global:SwitchMinute',
    '',
    '        $isNextDay = $false',
    '        $targetDate = $now',
    '',
    '        if ($currentMins -ge $switchMins) {',
    '            $isNextDay = $true',
    '            $targetDate = $now.AddDays(1)',
    '        }',
    '',
    '        if ($targetDate.DayOfWeek -eq [DayOfWeek]::Saturday) {',
    '            $targetDate = $targetDate.AddDays(2)',
    '            $isNextDay = $true',
    '        } elseif ($targetDate.DayOfWeek -eq [DayOfWeek]::Sunday) {',
    '            $targetDate = $targetDate.AddDays(1)',
    '            $isNextDay = $true',
    '        }',
    '',
    '        $ymd = $targetDate.ToString("yyyyMMdd")',
    '        $monthDay = $targetDate.ToString("M월 d일")',
    '        $daysKorean = @("일", "월", "화", "수", "목", "금", "토")',
    '        $dayName = $daysKorean[[int]$targetDate.DayOfWeek]',
    '',
    '        if ($isNextDay) {',
    '            $Global:TxtMealTitle.Text = "내일의 급식"',
    '        } else {',
    '            $Global:TxtMealTitle.Text = "오늘의 급식"',
    '        }',
    '        $Global:TxtMealDateBadge.Text = "$monthDay ($dayName)"',
    '',
    '        $url = "https://open.neis.go.kr/hub/mealServiceDietInfo?Type=json&pIndex=1&pSize=5&ATPT_OFCDC_SC_CODE=$($Global:OfficeCode)&SD_SCHUL_CODE=$($Global:SchoolCode)&MLSV_YMD=$ymd"',
    '',
    '        try {',
    '            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12',
    '            $response = Invoke-RestMethod -Uri $url -Method Get -TimeoutSec 5 -ErrorAction Stop',
    '',
    '            if ($response.mealServiceDietInfo -and $response.mealServiceDietInfo[1].row) {',
    '                $rows = $response.mealServiceDietInfo[1].row',
    '                $lunch = $rows | Where-Object { $_.MMEAL_SC_CODE -eq "2" } | Select-Object -First 1',
    '                if (!$lunch) { $lunch = $rows[0] }',
    '',
    '                $rawDish = $lunch.DDISH_NM',
    '                $cleanDish = $rawDish -replace "<br\\s*[/]?>", "`n"',
    '                if (!$Global:ShowAllergies) {',
    '                    $cleanDish = $cleanDish -replace "\\([0-9\\.\\s]+\\)", ""',
    '                }',
    '',
    '                $dishItems = @($cleanDish -split "`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ })',
    '                if ($dishItems.Count -eq 0) { $dishItems = @("등록된 급식 메뉴가 없습니다.") }',
    '                Render-MealMenu -items $dishItems',
    '                $calInfo = $lunch.CAL_INFO',
    '                if ($Global:ShowCalories -and $calInfo) {',
    '                    $Global:TxtMealCalories.Text = "열량: " + ($calInfo -replace "<br/>", " ")',
    '                    $Global:TxtMealApiCredit.Text = "나이스 Open API 연동"',
    '                } else {',
    '                    $Global:TxtMealCalories.Text = ""',
    '                    $Global:TxtMealApiCredit.Text = ""',
    '                }',
    '            } else {',
    '                Render-MealMenu -items @("등록된 급식 정보가 없습니다.", "(방학, 휴일 또는 식단 미등록)") -isFallback $true',
    '                $Global:TxtMealCalories.Text = ""',
    '                $Global:TxtMealApiCredit.Text = ""',
    '            }',
    '        } catch {',
    '            Render-MealMenu -items @("급식 정보를 불러올 수 없습니다.", "(오프라인 또는 NEIS 서버 점검)") -isFallback $true',
    '            $Global:TxtMealCalories.Text = ""',
    '            $Global:TxtMealApiCredit.Text = ""',
    '        }',
    '    }',
    '',
    '    # 9.5 나이스(NEIS) 학교 검색 (설정 창의 학교 검색에서 사용, office 코드 없이 전국 통합검색)',
    '    function Search-NeisSchool {',
    '        param([string]$Keyword)',
    '        $results = New-Object System.Collections.ArrayList',
    '        if ([string]::IsNullOrWhiteSpace($Keyword)) { return $results }',
    '        try {',
    '            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12',
    '            $encoded = [System.Uri]::EscapeDataString($Keyword)',
    '            $url = "https://open.neis.go.kr/hub/schoolInfo?Type=json&pIndex=1&pSize=20&SCHUL_NM=$encoded"',
    '            $response = Invoke-RestMethod -Uri $url -Method Get -TimeoutSec 5 -ErrorAction Stop',
    '            if ($response.schoolInfo -and $response.schoolInfo[1].row) {',
    '                foreach ($row in $response.schoolInfo[1].row) {',
    '                    [void]$results.Add([PSCustomObject]@{',
    '                        officeCode = $row.ATPT_OFCDC_SC_CODE',
    '                        officeName = $row.ATPT_OFCDC_SC_NM',
    '                        schoolCode = $row.SD_SCHUL_CODE',
    '                        schoolName = $row.SCHUL_NM',
    '                        location   = if ($row.ORG_RDNMA) { $row.ORG_RDNMA } else { $row.ORG_RDNDA }',
    '                    })',
    '                }',
    '            }',
    '        } catch { }',
    '        return $results',
    '    }',
    '',
    '    # 10. 할 일(TO-DO) 로드, 저장, 렌더링',
    '    function Load-Todos {',
    '        if (Test-Path $Global:TodoFile) {',
    '            try {',
    '                $json = Get-Content $Global:TodoFile -Raw -Encoding UTF8',
    '                $parsed = $json | ConvertFrom-Json',
    '                return @($parsed)',
    '            } catch {',
    '                return @()',
    '            }',
    '        }',
    '        # 최초 실행 시 스튜디오에서 설정한 할 일 목록으로 초기화',
    '        return @($Global:InitialTodosData)',
    '    }',
    '',
    '    function Save-Todos {',
    '        param($todosList)',
    '        $json = $todosList | ConvertTo-Json -Depth 4',
    '        [System.IO.File]::WriteAllText($Global:TodoFile, $json, [System.Text.Encoding]::UTF8)',
    '    }',
    '',
    '    function Render-Todos {',
    '        $Global:PnlTodoList.Children.Clear()',
    '        $todos = @(Load-Todos)',
    '        $remaining = @($todos | Where-Object { !$_.completed }).Count',
    '        $Global:TxtTodoCount.Text = "${remaining}개 남음"',
    '',
    '        # 스크롤 제한은 아이템을 다 채운 뒤 실제 필요한 높이를 측정해서 정확히 적용',
    '        $Global:SvTodoList.ClearValue([System.Windows.Controls.ScrollViewer]::HeightProperty)',
    '',
    '        foreach ($todo in $todos) {',
    '            $itemGrid = New-Object System.Windows.Controls.Grid',
    '            $c0 = New-Object System.Windows.Controls.ColumnDefinition',
    '            $c0.Width = [System.Windows.GridLength]::Auto',
    '            $c1 = New-Object System.Windows.Controls.ColumnDefinition',
    '            $c1.Width = [System.Windows.GridLength](New-Object System.Windows.GridLength(1, [System.Windows.GridUnitType]::Star))',
    '            $c2 = New-Object System.Windows.Controls.ColumnDefinition',
    '            $c2.Width = [System.Windows.GridLength](New-Object System.Windows.GridLength(24, [System.Windows.GridUnitType]::Pixel))',
    '            $itemGrid.ColumnDefinitions.Add($c0)',
    '            $itemGrid.ColumnDefinitions.Add($c1)',
    '            $itemGrid.ColumnDefinitions.Add($c2)',
    '            $itemGrid.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(0, 2, 0, 2))',
    '',
    '            # 드래그 순서변경 손잡이 (시뮬레이터의 GripVertical과 동일한 역할)',
    '            $grip = New-Object System.Windows.Controls.TextBlock',
    '            $grip.Text = [char]0x22EE + [char]0x22EE',
    '            $grip.FontSize = 10',
    '            # Background가 비어있으면 글자 잉크 부분만 클릭이 인식되는 WPF 특성 때문에,',
    '            # 손잡이 전체 영역이 클릭되도록 투명 배경을 명시적으로 지정',
    '            $grip.Background = [System.Windows.Media.Brushes]::Transparent',
    '            $grip.Padding = [System.Windows.Thickness](New-Object System.Windows.Thickness(2, 2, 2, 2))',
    '            $grip.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:Colors.TextSecondary)',
    '            $grip.VerticalAlignment = [System.Windows.VerticalAlignment]::Center',
    '            $grip.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(0, 0, 4, 0))',
    '            $grip.Cursor = [System.Windows.Input.Cursors]::SizeAll',
    '            $grip.Tag = $todo.id',
    '            [System.Windows.Controls.Grid]::SetColumn($grip, 0)',
    '',
    '            $grip.Add_MouseLeftButtonDown({',
    '                param($s, $e)',
    '                $Global:DragTodoId = $s.Tag',
    '                [void]$s.CaptureMouse()',
    '                $e.Handled = $true',
    '            })',
    '',
    '            $grip.Add_MouseMove({',
    '                param($s, $e)',
    '                if ($Global:DragTodoId -and $e.LeftButton -eq [System.Windows.Input.MouseButtonState]::Pressed) {',
    '                    if ($s.Parent) { $s.Parent.Opacity = 0.4 }',
    '                }',
    '            })',
    '',
    '            $grip.Add_MouseLeftButtonUp({',
    '                param($s, $e)',
    '                if ($Global:DragTodoId) {',
    '                    $s.ReleaseMouseCapture()',
    '                    $draggedId = $Global:DragTodoId',
    '                    $Global:DragTodoId = $null',
    '                    $dropPos = $e.GetPosition($Global:PnlTodoList)',
    '',
    '                    $targetIndex = $Global:PnlTodoList.Children.Count - 1',
    '                    for ($i = 0; $i -lt $Global:PnlTodoList.Children.Count; $i++) {',
    '                        $child = $Global:PnlTodoList.Children[$i]',
    '                        $topLeft = $child.TranslatePoint((New-Object System.Windows.Point(0, 0)), $Global:PnlTodoList)',
    '                        $childMidY = $topLeft.Y + ($child.ActualHeight / 2)',
    '                        if ($dropPos.Y -lt $childMidY) { $targetIndex = $i; break }',
    '                    }',
    '',
    '                    $curTodos = @(Load-Todos)',
    '                    $fromIndex = -1',
    '                    for ($i = 0; $i -lt $curTodos.Count; $i++) { if ($curTodos[$i].id -eq $draggedId) { $fromIndex = $i } }',
    '                    if ($fromIndex -ge 0 -and $targetIndex -ne $fromIndex) {',
    '                        $moved = $curTodos[$fromIndex]',
    '                        $rest = New-Object System.Collections.ArrayList',
    '                        for ($i = 0; $i -lt $curTodos.Count; $i++) { if ($i -ne $fromIndex) { [void]$rest.Add($curTodos[$i]) } }',
    '                        $insertAt = $targetIndex',
    '                        if ($targetIndex -gt $fromIndex) { $insertAt = $targetIndex - 1 }',
    '                        $insertAt = [Math]::Max(0, [Math]::Min($insertAt, $rest.Count))',
    '                        $rest.Insert($insertAt, $moved) | Out-Null',
    '                        Save-Todos @($rest)',
    '                    }',
    '                    Render-Todos',
    '                }',
    '            })',
    '',
    '            $todoColor = if ($todo.completed) { $Global:Colors.TextSecondary } else { $Global:Colors.TextPrimary }',
    '            $chk = New-Object System.Windows.Controls.CheckBox',
    '            # 완료된 항목은 시뮬레이터처럼 취소선 + 흐림 처리',
    '            $todoLabel = New-Object System.Windows.Controls.TextBlock',
    '            $todoLabel.Text = $todo.text',
    '            $todoLabel.FontSize = 11',
    '            if ($todo.completed) { $todoLabel.TextDecorations = [System.Windows.TextDecorations]::Strikethrough }',
    '            $chk.Content = $todoLabel',
    '            $chk.IsChecked = [bool]$todo.completed',
    '            $chk.FontSize = 11',
    '            $chk.Opacity = if ($todo.completed) { 0.6 } else { 1.0 }',
    '            $chk.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($todoColor)',
    '            $chk.Tag = $todo.id',
    '            [System.Windows.Controls.Grid]::SetColumn($chk, 1)',
    '',
    '            $chk.Add_Click({',
    '                param($s, $ev)',
    '                $id = $s.Tag',
    '                $curTodos = Load-Todos',
    '                foreach ($t in $curTodos) {',
    '                    if ($t.id -eq $id) {',
    '                        $t.completed = [bool]$s.IsChecked',
    '                    }',
    '                }',
    '                Save-Todos $curTodos',
    '                Render-Todos',
    '            })',
    '',
    '            $btnDel = New-Object System.Windows.Controls.Button',
    '            $btnDel.Content = "✕"',
    '            $btnDel.Width = 20',
    '            $btnDel.Height = 20',
    '            $btnDel.Background = [System.Windows.Media.Brushes]::Transparent',
    '            $btnDel.Foreground = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:Colors.TextSecondary)',
    '            $btnDel.BorderThickness = [System.Windows.Thickness]0',
    '            $btnDel.Cursor = [System.Windows.Input.Cursors]::Hand',
    '            $btnDel.FontSize = 10',
    '            $btnDel.Tag = $todo.id',
    '            [System.Windows.Controls.Grid]::SetColumn($btnDel, 2)',
    '',
    '            $btnDel.Add_Click({',
    '                param($s, $ev)',
    '                $id = $s.Tag',
    '                $curTodos = Load-Todos | Where-Object { $_.id -ne $id }',
    '                Save-Todos $curTodos',
    '                Render-Todos',
    '            })',
    '',
    '            $itemGrid.Children.Add($grip) | Out-Null',
    '            $itemGrid.Children.Add($chk) | Out-Null',
    '            $itemGrid.Children.Add($btnDel) | Out-Null',
    '            $Global:PnlTodoList.Children.Add($itemGrid) | Out-Null',
    '        }',
    '',
    '        Update-TodoScrollCap',
    '    }',
    '',
    '    function Add-NewTodo {',
    '        $text = $Global:TxtNewTodo.Text.Trim()',
    '        if ($text) {',
    '            $todos = @(Load-Todos)',
    '            $newTodo = [PSCustomObject]@{',
    '                id = (Get-Date).Ticks.ToString()',
    '                text = $text',
    '                completed = $false',
    '                createdAt = (Get-Date).ToString("yyyy-MM-dd HH:mm")',
    '            }',
    '            $todos += $newTodo',
    '            Save-Todos $todos',
    '            $Global:TxtNewTodo.Text = ""',
    '            Render-Todos',
    '        }',
    '    }',
    '',
    '    # 11. 시계 및 타이머 (DispatcherTimer)',
    '    function Update-AllData {',
    '        $now = Get-Date',
    '        $daysKorean = @("일", "월", "화", "수", "목", "금", "토")',
    '        $dayName = $daysKorean[[int]$now.DayOfWeek]',
    '        $Global:TxtCurrentDate.Text = $now.ToString("yyyy년 M월 d일") + " ($dayName)"',
    '        $Global:TxtCurrentTime.Text = $now.ToString("tt hh:mm:ss")',
    '',
    '        Update-DDays',
    '        Update-Timetable',
    '        Update-MealInfo',
    '    }',
    '',
    '    # 12. 설정 저장 → config.json 반영 → 위젯 전체 재구성. 창을 새로 열지 않고 그 자리에서 바로 반영됨.',
    '    function Rebuild-Widget {',
    '        $xamlFragment = Build-WidgetXaml',
    '        $sr = New-Object System.IO.StringReader($xamlFragment)',
    '        $xr = [System.Xml.XmlReader]::Create($sr)',
    '        $Global:Window.Content = [System.Windows.Markup.XamlReader]::Load($xr)',
    '        Bind-WidgetControls',
    '        Render-Icons',
    '        $Global:Window.Topmost = $Global:AlwaysOnTop',
    '        $Global:Window.Width = [Math]::Round(340 * $Global:FontScale)',
    '        $startDaysKorean = @("일", "월", "화", "수", "목", "금", "토")',
    '        $startDayName = $startDaysKorean[[int](Get-Date).DayOfWeek]',
    '        $Global:SelectedDay = if ($Global:DaysKorean5 -contains $startDayName) { $startDayName } else { "월" }',
    '        Init-DaySelector',
    '        Update-AllData',
    '        Render-Todos',
    '        Snap-ToRightTop',
    '        Sync-AutoStart',
    '    }',
    '',
    '    function Apply-NewConfig {',
    '        param($NewConfig)',
    '        Save-Config $NewConfig',
    '        Sync-GlobalsFromConfig $NewConfig',
    '        Rebuild-Widget',
    '    }',
    '',
    ...buildSettingsWindowLines(),
    '',
    '    # 13. 창 생성 및 최초 렌더링',
    '    Sync-GlobalsFromConfig (Load-Config)',
    '',
    '    $shellXaml = @"',
    '<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"',
    '    Title="NEWSchoolWidget (진화형) - 학교 생활 위젯"',
    '    WindowStyle="None" ResizeMode="NoResize" AllowsTransparency="True" Background="Transparent"',
    '    ShowInTaskbar="False" SizeToContent="Height" UseLayoutRounding="True" SnapsToDevicePixels="True"',
    '    FontFamily="맑은 고딕, Segoe UI, Malgun Gothic">',
    '</Window>',
    '"@',
    '    $shellReader = New-Object System.IO.StringReader($shellXaml)',
    '    $shellXmlReader = [System.Xml.XmlReader]::Create($shellReader)',
    '    $Global:Window = [System.Windows.Markup.XamlReader]::Load($shellXmlReader)',
    '    $Global:Window.WindowStartupLocation = [System.Windows.WindowStartupLocation]::Manual',
    '',
    '    $Global:Window.Add_MouseLeftButtonDown({',
    '        param($sender, $e)',
    '        if ($e.OriginalSource -isnot [System.Windows.Controls.TextBox] -and $e.OriginalSource -isnot [System.Windows.Controls.Button] -and $e.OriginalSource -isnot [System.Windows.Controls.CheckBox]) {',
    '            $Global:IsDragging = $true',
    '            $Global:Window.DragMove()',
    '        }',
    '    })',
    '',
    '    $Global:Window.Add_PreviewMouseLeftButtonUp({',
    '        param($sender, $e)',
    '        if ($Global:IsDragging) {',
    '            $Global:IsDragging = $false',
    '            Snap-ToRightTop',
    '        }',
    '    })',
    '',
    '    $Global:Window.Add_Loaded({',
    '        try {',
    '            # 창이 뿅 나타나지 않고 부드럽게 페이드인 되도록',
    '            $fadeAnim = New-Object System.Windows.Media.Animation.DoubleAnimation',
    '            $fadeAnim.From = 0',
    '            $fadeAnim.To = 1',
    '            $fadeAnim.Duration = New-Object System.Windows.Duration ([TimeSpan]::FromMilliseconds(220))',
    '            $Global:Window.BeginAnimation([System.Windows.Window]::OpacityProperty, $fadeAnim)',
    '        } catch { }',
    '    })',
    '',
    '    Rebuild-Widget',
    '',
    '    $timer = New-Object System.Windows.Threading.DispatcherTimer',
    '    $timer.Interval = [TimeSpan]::FromSeconds(1)',
    '    $timer.Add_Tick({',
    '        $now = Get-Date',
    '        $Global:TxtCurrentTime.Text = $now.ToString("tt hh:mm:ss")',
    '        if ($now.Second -eq 0 -and ($now.Minute -eq 0 -or $now.Minute -eq 30)) {',
    '            Update-AllData',
    '        }',
    '    })',
    '    $timer.Start()',
    '',
    '    # 14. 윈도우 표시 (모달 대화상자)',
    '    $Global:Window.ShowDialog() | Out-Null',
    '} catch {',
    '    Add-Type -AssemblyName System.Windows.Forms',
    '    [System.Windows.Forms.MessageBox]::Show("학교 생활 위젯 실행 중 오류 발생:`r`n`r`n" + $_.Exception.Message + "`r`n`r`n상세:`r`n" + $_.Exception.ToString(), "학교 생활 위젯 오류", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error)',
    '}',
  ];

  return lines.join('\r\n');
}

/**
 * Generate a 100% standalone, self-contained .bat file
 * that can be double-clicked directly without needing a separate .ps1 file.
 */
export function generateAllInOneBat(config: WidgetConfig): string {
  const psScript = generatePowerShellScript(config);

  const batHeader = [
    '@echo off',
    'setlocal enabledelayedexpansion',
    'title NEWSchoolWidget-Evolved (학교 생활 위젯)',
    'cd /d "%~dp0"',
    '',
    'rem ============================================================================',
    'rem   [NEWSchoolWidget (진화형) - 단일 통합 원클릭 실행 배치 파일]',
    'rem   - 별도의 .ps1 파일 없이 이 .bat 파일 하나만으로 즉시 위젯이 실행됩니다.',
    'rem   - Windows ExecutionPolicy 제한을 자동으로 우회(Bypass)하여 즉시 실행합니다.',
    'rem ============================================================================',
    '',
    'set "BAT_PATH=%~f0"',
    'powershell.exe -NoProfile -ExecutionPolicy Bypass -Sta -WindowStyle Hidden -Command "$f=$env:BAT_PATH; if(Test-Path -LiteralPath $f){ $c=[System.IO.File]::ReadAllText($f,[System.Text.Encoding]::UTF8); $marker=\'###POWERSHELL_START_POINT###\'; $i=$c.LastIndexOf($marker); if($i -ge 0){ $code=$c.Substring($i+$marker.Length); $tempPs1=[System.IO.Path]::Combine($env:TEMP,\'NEWSchoolWidget_Evolved_Runner.ps1\'); [System.IO.File]::WriteAllText($tempPs1,$code,[System.Text.Encoding]::UTF8); Start-Process powershell.exe -WindowStyle Hidden -ArgumentList @(\'-NoProfile\',\'-ExecutionPolicy\',\'Bypass\',\'-Sta\',\'-WindowStyle\',\'Hidden\',\'-File\',$tempPs1) } }" >nul 2>&1',
    '',
    'exit /b 0',
    '',
    '###POWERSHELL_START_POINT###',
  ].join('\r\n');

  return `${batHeader}\r\n${psScript}`;
}
