// 위젯 자체 "⚙ 설정" 창을 만드는 PowerShell/WPF 코드.
// powerShellGenerator.ts가 조립하는 큰 스크립트의 일부로 그대로 이어붙여진다(같은 string[] + join 패턴).
// 여기 정의되는 모든 컨트롤/드래프트 상태는 $Global: 스코프를 쓴다 — 이 파일의 다른 함수들과 마찬가지로,
// Add_Click 등 이벤트 스크립트블록은 정의된 함수 스코프의 지역변수를 자동으로 클로저 캡처하지 않기 때문.
//
// 이 창이 하는 일: 웹 Studio(ConfigPanel.tsx)와 동일한 4개 그룹(학교&급식/D-Day/시간표/디자인&스냅)을
// 위젯 자신 안에서 편집하게 해서, 설정을 바꿀 때마다 웹사이트를 다시 들르지 않아도 되게 한다.
// "저장"을 누르면 Apply-NewConfig가 config.json 저장 → 전역 갱신 → Rebuild-Widget까지 한 번에 처리한다.
export function buildSettingsWindowLines(): string[] {
  return [
    '    # 16. 위젯 자체 "설정" 창 — 학교/급식/시간표/D-Day/디자인/자동시작을 여기서 바로 편집.',
    '    # 저장하면 config.json에 즉시 반영되고 위젯이 재다운로드 없이 바로 갱신됨(Apply-NewConfig).',
    '    $Global:ThemeChoices = @(',
    '        @{ Id = "dark-acrylic";  Name = "모던 다크 글래스" },',
    '        @{ Id = "light-acrylic"; Name = "클린 라이트 아크릴" },',
    '        @{ Id = "slate-glass";   Name = "실버 슬레이트" },',
    '        @{ Id = "emerald-glass"; Name = "에메랄드 포레스트" },',
    '        @{ Id = "indigo-glass";  Name = "딥 인디고 블루" },',
    '        @{ Id = "sakura-glass";  Name = "사쿠라 핑크" },',
    '        @{ Id = "amber-glass";   Name = "앰버 선라이즈" },',
    '        @{ Id = "mono-glass";    Name = "모노 하이컨트라스트" }',
    '    )',
    '',
    '    function Update-DDayListBoxDisplay {',
    '        $Global:SetLstDDays.Items.Clear()',
    '        for ($i = 0; $i -lt $Global:SettingsDraftDDays.Count; $i++) {',
    '            $d = $Global:SettingsDraftDDays[$i]',
    '            [void]$Global:SetLstDDays.Items.Add("$($i + 1). $($d.title) — $($d.targetDate)")',
    '        }',
    '    }',
    '',
    '    function Get-TimetableBoxKey {',
    '        param([string]$Day, [int]$Period)',
    '        return "$Day" + "_" + "$Period"',
    '    }',
    '',
    '    function Show-SettingsWindow {',
    '        $xaml = @"',
    '<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"',
    '    Title="위젯 설정" Width="440" SizeToContent="Height" MaxHeight="720" ResizeMode="NoResize"',
    '    WindowStartupLocation="CenterOwner" Background="#0F172A" Foreground="#E2E8F0" FontFamily="맑은 고딕, Segoe UI">',
    '    <ScrollViewer VerticalScrollBarVisibility="Auto" MaxHeight="700">',
    '    <StackPanel Margin="14">',
    '        <TabControl x:Name="TabSettings" Background="#0F172A" BorderThickness="0">',
    '            <TabItem Header="학교 &amp; 급식">',
    '                <StackPanel Margin="8">',
    '                    <TextBlock Text="현재 학교" FontWeight="Bold" Margin="0,4,0,2"/>',
    '                    <TextBlock x:Name="TxtCurrentSchool" TextWrapping="Wrap" Foreground="#93C5FD" Margin="0,0,0,8"/>',
    '                    <TextBlock Text="학교 검색 (나이스 전국 통합검색)" Margin="0,4,0,2"/>',
    '                    <Grid Margin="0,0,0,4">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="Auto"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <TextBox x:Name="TxtSchoolSearch" Grid.Column="0" Height="26" VerticalContentAlignment="Center" Margin="0,0,4,0"/>',
    '                        <Button x:Name="BtnSchoolSearch" Grid.Column="1" Content="검색" Width="56" Height="26"/>',
    '                    </Grid>',
    '                    <ListBox x:Name="LstSchoolResults" Height="110" Margin="0,0,0,10"/>',
    '                    <TextBlock Text="급식 전환 시각 (이 시각 이후엔 내일 급식 표시, HH:mm)" Margin="0,4,0,2"/>',
    '                    <TextBox x:Name="TxtMealSwitchTime" Width="80" Height="24" HorizontalAlignment="Left" Margin="0,0,0,8"/>',
    '                    <CheckBox x:Name="ChkShowAllergies" Content="알레르기 유발물질 번호 표시" Margin="0,2,0,4"/>',
    '                    <CheckBox x:Name="ChkShowCalories" Content="예상 열량(Kcal) 표시" Margin="0,2,0,4"/>',
    '                </StackPanel>',
    '            </TabItem>',
    '            <TabItem Header="D-Day">',
    '                <StackPanel Margin="8">',
    '                    <Grid Margin="0,4,0,6">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="110"/>',
    '                            <ColumnDefinition Width="Auto"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <TextBox x:Name="TxtNewDDayTitle" Grid.Column="0" Height="26" Margin="0,0,4,0" VerticalContentAlignment="Center"/>',
    '                        <TextBox x:Name="TxtNewDDayDate" Grid.Column="1" Height="26" Margin="0,0,4,0" VerticalContentAlignment="Center" Text="YYYY-MM-DD"/>',
    '                        <Button x:Name="BtnAddDDay" Grid.Column="2" Content="추가" Width="50" Height="26"/>',
    '                    </Grid>',
    '                    <ListBox x:Name="LstDDays" Height="220" Margin="0,0,0,6"/>',
    '                    <StackPanel Orientation="Horizontal">',
    '                        <Button x:Name="BtnDDayUp" Content="위로" Width="60" Height="24" Margin="0,0,4,0"/>',
    '                        <Button x:Name="BtnDDayDown" Content="아래로" Width="60" Height="24" Margin="0,0,4,0"/>',
    '                        <Button x:Name="BtnDDayDelete" Content="삭제" Width="60" Height="24"/>',
    '                    </StackPanel>',
    '                </StackPanel>',
    '            </TabItem>',
    '            <TabItem Header="시간표">',
    '                <StackPanel Margin="8">',
    '                    <TextBlock Text="월~금 시간표 (빈칸은 - 로 표시됩니다)" Margin="0,4,0,6"/>',
    '                    <StackPanel x:Name="PnlTimetableEditor"/>',
    '                </StackPanel>',
    '            </TabItem>',
    '            <TabItem Header="디자인 &amp; 스냅">',
    '                <StackPanel Margin="8">',
    '                    <TextBlock Text="테마" FontWeight="Bold" Margin="0,4,0,2"/>',
    '                    <ComboBox x:Name="CmbTheme" Height="26" Margin="0,0,0,8"/>',
    '                    <TextBlock Text="커스텀 강조색" Margin="0,4,0,2"/>',
    '                    <Grid Margin="0,0,0,8">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="Auto"/>',
    '                            <ColumnDefinition Width="Auto"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Button x:Name="BtnAccentColor" Grid.Column="0" Content="색상 선택" Width="90" Height="26" Margin="0,0,6,0"/>',
    '                        <Button x:Name="BtnAccentReset" Grid.Column="1" Content="테마 기본색으로" Width="110" Height="26"/>',
    '                    </Grid>',
    '                    <TextBlock Text="모서리 둥근 정도" Margin="0,4,0,2"/>',
    '                    <Slider x:Name="SldRadius" Minimum="4" Maximum="28" Margin="0,0,0,8"/>',
    '                    <TextBlock Text="글씨 크기" Margin="0,0,0,2"/>',
    '                    <Slider x:Name="SldFontScale" Minimum="0.85" Maximum="1.3" Margin="0,0,0,8"/>',
    '                    <TextBlock Text="투명도" Margin="0,0,0,2"/>',
    '                    <Slider x:Name="SldOpacity" Minimum="0.6" Maximum="1.0" Margin="0,0,0,8"/>',
    '                    <TextBlock Text="자동 스냅 위치" Margin="0,0,0,2"/>',
    '                    <StackPanel Orientation="Horizontal" Margin="0,0,0,8">',
    '                        <RadioButton x:Name="RbSnapLeft" Content="왼쪽 상단" GroupName="SnapSide" Margin="0,0,16,0"/>',
    '                        <RadioButton x:Name="RbSnapRight" Content="오른쪽 상단" GroupName="SnapSide"/>',
    '                    </StackPanel>',
    '                    <TextBlock Text="스냅 여백(px)" Margin="0,0,0,2"/>',
    '                    <Slider x:Name="SldSnapMargin" Minimum="0" Maximum="60" Margin="0,0,0,8"/>',
    '                    <CheckBox x:Name="ChkAlwaysOnTop" Content="항상 위에 표시" Margin="0,2,0,4"/>',
    '                    <CheckBox x:Name="ChkAutoStart" Content="컴퓨터 시작 시 자동 실행" Margin="0,2,0,4"/>',
    '                </StackPanel>',
    '            </TabItem>',
    '        </TabControl>',
    '        <StackPanel Orientation="Horizontal" HorizontalAlignment="Right" Margin="0,14,0,0">',
    '            <Button x:Name="BtnSettingsCancel" Content="취소" Width="72" Height="28" Margin="0,0,8,0"/>',
    '            <Button x:Name="BtnSettingsSave" Content="저장" Width="72" Height="28" Background="#2563EB" Foreground="White" FontWeight="Bold"/>',
    '        </StackPanel>',
    '    </StackPanel>',
    '    </ScrollViewer>',
    '</Window>',
    '"@',
    '        $sr = New-Object System.IO.StringReader($xaml)',
    '        $xr = [System.Xml.XmlReader]::Create($sr)',
    '        $win = [System.Windows.Markup.XamlReader]::Load($xr)',
    '        $win.Owner = $Global:Window',
    '',
    '        $Global:SetTxtCurrentSchool = $win.FindName("TxtCurrentSchool")',
    '        $Global:SetTxtSchoolSearch  = $win.FindName("TxtSchoolSearch")',
    '        $Global:SetBtnSchoolSearch  = $win.FindName("BtnSchoolSearch")',
    '        $Global:SetLstSchoolResults = $win.FindName("LstSchoolResults")',
    '        $Global:SetTxtMealSwitchTime = $win.FindName("TxtMealSwitchTime")',
    '        $Global:SetChkShowAllergies = $win.FindName("ChkShowAllergies")',
    '        $Global:SetChkShowCalories  = $win.FindName("ChkShowCalories")',
    '        $Global:SetTxtNewDDayTitle  = $win.FindName("TxtNewDDayTitle")',
    '        $Global:SetTxtNewDDayDate   = $win.FindName("TxtNewDDayDate")',
    '        $Global:SetBtnAddDDay       = $win.FindName("BtnAddDDay")',
    '        $Global:SetLstDDays         = $win.FindName("LstDDays")',
    '        $Global:SetBtnDDayUp        = $win.FindName("BtnDDayUp")',
    '        $Global:SetBtnDDayDown      = $win.FindName("BtnDDayDown")',
    '        $Global:SetBtnDDayDelete    = $win.FindName("BtnDDayDelete")',
    '        $Global:SetPnlTimetableEditor = $win.FindName("PnlTimetableEditor")',
    '        $Global:SetCmbTheme         = $win.FindName("CmbTheme")',
    '        $Global:SetBtnAccentColor   = $win.FindName("BtnAccentColor")',
    '        $Global:SetBtnAccentReset   = $win.FindName("BtnAccentReset")',
    '        $Global:SetSldRadius        = $win.FindName("SldRadius")',
    '        $Global:SetSldFontScale     = $win.FindName("SldFontScale")',
    '        $Global:SetSldOpacity       = $win.FindName("SldOpacity")',
    '        $Global:SetRbSnapLeft       = $win.FindName("RbSnapLeft")',
    '        $Global:SetRbSnapRight      = $win.FindName("RbSnapRight")',
    '        $Global:SetSldSnapMargin    = $win.FindName("SldSnapMargin")',
    '        $Global:SetChkAlwaysOnTop   = $win.FindName("ChkAlwaysOnTop")',
    '        $Global:SetChkAutoStart     = $win.FindName("ChkAutoStart")',
    '        $Global:SetBtnCancel        = $win.FindName("BtnSettingsCancel")',
    '        $Global:SetBtnSave          = $win.FindName("BtnSettingsSave")',
    '',
    '        # --- 드래프트 상태 초기화 (저장 누르기 전까지는 실제 설정에 영향 없음) ---',
    '        $Global:SettingsDraftSchool = $Global:Config.school',
    '        $Global:SettingsDraftDDays = New-Object System.Collections.ArrayList',
    '        foreach ($d in $Global:DDaysData) { [void]$Global:SettingsDraftDDays.Add([PSCustomObject]@{ id = $d.id; title = $d.title; targetDate = $d.targetDate }) }',
    '        $Global:SettingsDraftAccent = $Global:Config.customAccentColor',
    '        $Global:SettingsDraftTimetableBoxes = @{}',
    '',
    '        $Global:SetTxtCurrentSchool.Text = "$($Global:SettingsDraftSchool.schoolName) ($($Global:SettingsDraftSchool.officeName))"',
    '        $Global:SetTxtMealSwitchTime.Text = "$($Global:Config.mealSwitchTime)"',
    '        $Global:SetChkShowAllergies.IsChecked = [bool]$Global:Config.showAllergies',
    '        $Global:SetChkShowCalories.IsChecked = [bool]$Global:Config.showCalories',
    '        Update-DDayListBoxDisplay',
    '',
    '        foreach ($choice in $Global:ThemeChoices) { [void]$Global:SetCmbTheme.Items.Add($choice.Name) }',
    '        $curThemeIndex = 0',
    '        for ($i = 0; $i -lt $Global:ThemeChoices.Count; $i++) { if ($Global:ThemeChoices[$i].Id -eq $Global:Config.theme) { $curThemeIndex = $i } }',
    '        $Global:SetCmbTheme.SelectedIndex = $curThemeIndex',
    '        $Global:SetSldRadius.Value = $Global:CornerRadius',
    '        $Global:SetSldFontScale.Value = $Global:FontScale',
    '        $Global:SetSldOpacity.Value = $Global:Opacity',
    '        if ($Global:Config.snapSide -eq "left") { $Global:SetRbSnapLeft.IsChecked = $true } else { $Global:SetRbSnapRight.IsChecked = $true }',
    '        $Global:SetSldSnapMargin.Value = $Global:SnapMargin',
    '        $Global:SetChkAlwaysOnTop.IsChecked = $Global:AlwaysOnTop',
    '        $Global:SetChkAutoStart.IsChecked = $Global:AutoStartOnLogin',
    '',
    '        # --- 시간표 편집 그리드 (요일별 7교시 텍스트박스, 프로그래밍 방식 생성) ---',
    '        $days5 = @("월", "화", "수", "목", "금")',
    '        foreach ($day in $days5) {',
    '            $rowLabel = New-Object System.Windows.Controls.TextBlock',
    '            $rowLabel.Text = "$day 요일"',
    '            $rowLabel.FontWeight = [System.Windows.FontWeights]::Bold',
    '            $rowLabel.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(0, 6, 0, 2))',
    '            [void]$Global:SetPnlTimetableEditor.Children.Add($rowLabel)',
    '',
    '            $rowPanel = New-Object System.Windows.Controls.Primitives.UniformGrid',
    '            $rowPanel.Columns = 7',
    '            $daySchedule = $Global:TimetableData | Where-Object { $_.day -eq $day }',
    '            for ($p = 1; $p -le 7; $p++) {',
    '                $existing = "-"',
    '                if ($daySchedule -and $daySchedule.periods -and $daySchedule.periods.Count -ge $p) { $existing = $daySchedule.periods[$p - 1] }',
    '                $box = New-Object System.Windows.Controls.TextBox',
    '                $box.Text = $existing',
    '                $box.Margin = [System.Windows.Thickness](New-Object System.Windows.Thickness(1))',
    '                $box.FontSize = 10',
    '                $key = Get-TimetableBoxKey -Day $day -Period $p',
    '                $Global:SettingsDraftTimetableBoxes[$key] = $box',
    '                [void]$rowPanel.Children.Add($box)',
    '            }',
    '            [void]$Global:SetPnlTimetableEditor.Children.Add($rowPanel)',
    '        }',
    '',
    '        # --- 이벤트 ---',
    '        $Global:SetBtnSchoolSearch.Add_Click({',
    '            $kw = $Global:SetTxtSchoolSearch.Text.Trim()',
    '            $Global:SetLstSchoolResults.Items.Clear()',
    '            if (-not $kw) { return }',
    '            $found = Search-NeisSchool -Keyword $kw',
    '            if ($found.Count -eq 0) {',
    '                [void]$Global:SetLstSchoolResults.Items.Add("검색 결과가 없거나 인터넷 연결을 확인해 주세요.")',
    '                return',
    '            }',
    '            foreach ($r in $found) {',
    '                $item = New-Object System.Windows.Controls.ListBoxItem',
    '                $item.Content = "$($r.schoolName) ($($r.officeName))"',
    '                $item.Tag = $r',
    '                [void]$Global:SetLstSchoolResults.Items.Add($item)',
    '            }',
    '        })',
    '        $Global:SetLstSchoolResults.Add_MouseDoubleClick({',
    '            $sel = $Global:SetLstSchoolResults.SelectedItem',
    '            if ($sel -and $sel.Tag) {',
    '                $Global:SettingsDraftSchool = $sel.Tag',
    '                $Global:SetTxtCurrentSchool.Text = "선택됨: $($sel.Tag.schoolName) ($($sel.Tag.officeName))"',
    '            }',
    '        })',
    '',
    '        $Global:SetBtnAddDDay.Add_Click({',
    '            $title = $Global:SetTxtNewDDayTitle.Text.Trim()',
    '            $dateText = $Global:SetTxtNewDDayDate.Text.Trim()',
    '            $parsedDate = [DateTime]::MinValue',
    '            if ($title -and [DateTime]::TryParse($dateText, [ref]$parsedDate)) {',
    '                [void]$Global:SettingsDraftDDays.Add([PSCustomObject]@{',
    '                    id = (Get-Date).Ticks.ToString()',
    '                    title = $title',
    '                    targetDate = $parsedDate.ToString("yyyy-MM-dd")',
    '                })',
    '                $Global:SetTxtNewDDayTitle.Text = ""',
    '                $Global:SetTxtNewDDayDate.Text = "YYYY-MM-DD"',
    '                Update-DDayListBoxDisplay',
    '            } else {',
    '                [System.Windows.MessageBox]::Show("제목과 날짜(YYYY-MM-DD)를 정확히 입력해 주세요.", "D-Day 추가") | Out-Null',
    '            }',
    '        })',
    '        $Global:SetBtnDDayDelete.Add_Click({',
    '            $idx = $Global:SetLstDDays.SelectedIndex',
    '            if ($idx -ge 0) { $Global:SettingsDraftDDays.RemoveAt($idx); Update-DDayListBoxDisplay }',
    '        })',
    '        $Global:SetBtnDDayUp.Add_Click({',
    '            $idx = $Global:SetLstDDays.SelectedIndex',
    '            if ($idx -gt 0) {',
    '                $tmp = $Global:SettingsDraftDDays[$idx - 1]',
    '                $Global:SettingsDraftDDays[$idx - 1] = $Global:SettingsDraftDDays[$idx]',
    '                $Global:SettingsDraftDDays[$idx] = $tmp',
    '                Update-DDayListBoxDisplay',
    '                $Global:SetLstDDays.SelectedIndex = $idx - 1',
    '            }',
    '        })',
    '        $Global:SetBtnDDayDown.Add_Click({',
    '            $idx = $Global:SetLstDDays.SelectedIndex',
    '            if ($idx -ge 0 -and $idx -lt ($Global:SettingsDraftDDays.Count - 1)) {',
    '                $tmp = $Global:SettingsDraftDDays[$idx + 1]',
    '                $Global:SettingsDraftDDays[$idx + 1] = $Global:SettingsDraftDDays[$idx]',
    '                $Global:SettingsDraftDDays[$idx] = $tmp',
    '                Update-DDayListBoxDisplay',
    '                $Global:SetLstDDays.SelectedIndex = $idx + 1',
    '            }',
    '        })',
    '',
    '        $Global:SetBtnAccentColor.Add_Click({',
    '            $dlg = New-Object System.Windows.Forms.ColorDialog',
    '            $dlg.FullOpen = $true',
    '            if ($Global:SettingsDraftAccent) {',
    '                try {',
    '                    $existingColor = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:SettingsDraftAccent).Color',
    '                    $dlg.Color = [System.Drawing.Color]::FromArgb($existingColor.R, $existingColor.G, $existingColor.B)',
    '                } catch { }',
    '            }',
    '            if ($dlg.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {',
    '                $Global:SettingsDraftAccent = "#{0:X2}{1:X2}{2:X2}" -f $dlg.Color.R, $dlg.Color.G, $dlg.Color.B',
    '                $Global:SetBtnAccentColor.Background = (New-Object System.Windows.Media.BrushConverter).ConvertFromString($Global:SettingsDraftAccent)',
    '            }',
    '        })',
    '        $Global:SetBtnAccentReset.Add_Click({',
    '            $Global:SettingsDraftAccent = $null',
    '            $Global:SetBtnAccentColor.ClearValue([System.Windows.Controls.Control]::BackgroundProperty)',
    '        })',
    '',
    '        $Global:SetBtnCancel.Add_Click({ $win.DialogResult = $false; $win.Close() })',
    '        $Global:SetBtnSave.Add_Click({',
    '            $newTimetable = New-Object System.Collections.ArrayList',
    '            foreach ($day in $days5) {',
    '                $periodsArr = New-Object System.Collections.ArrayList',
    '                for ($p = 1; $p -le 7; $p++) {',
    '                    $key = Get-TimetableBoxKey -Day $day -Period $p',
    '                    [void]$periodsArr.Add($Global:SettingsDraftTimetableBoxes[$key].Text)',
    '                }',
    '                [void]$newTimetable.Add([PSCustomObject]@{ day = $day; periods = @($periodsArr) })',
    '            }',
    '',
    '            $selectedTheme = $Global:ThemeChoices[$Global:SetCmbTheme.SelectedIndex].Id',
    '            $snapSideNew = if ($Global:SetRbSnapLeft.IsChecked) { "left" } else { "right" }',
    '',
    '            $newConfig = $Global:Config | ConvertTo-Json -Depth 10 | ConvertFrom-Json',
    '            $newConfig.school = $Global:SettingsDraftSchool',
    '            $newConfig.ddays = @($Global:SettingsDraftDDays)',
    '            $newConfig.timetable = @($newTimetable)',
    '            $newConfig.mealSwitchTime = $Global:SetTxtMealSwitchTime.Text.Trim()',
    '            $newConfig.showAllergies = [bool]$Global:SetChkShowAllergies.IsChecked',
    '            $newConfig.showCalories = [bool]$Global:SetChkShowCalories.IsChecked',
    '            $newConfig.theme = $selectedTheme',
    '            $newConfig | Add-Member -NotePropertyName "customAccentColor" -NotePropertyValue $Global:SettingsDraftAccent -Force',
    '            $newConfig.cornerRadius = $Global:SetSldRadius.Value',
    '            $newConfig.fontScale = $Global:SetSldFontScale.Value',
    '            $newConfig.opacity = $Global:SetSldOpacity.Value',
    '            $newConfig.snapSide = $snapSideNew',
    '            $newConfig.snapMargin = [int]$Global:SetSldSnapMargin.Value',
    '            $newConfig.alwaysOnTop = [bool]$Global:SetChkAlwaysOnTop.IsChecked',
    '            $newConfig.autoStartOnLogin = [bool]$Global:SetChkAutoStart.IsChecked',
    '',
    '            $win.DialogResult = $true',
    '            $win.Close()',
    '            Apply-NewConfig $newConfig',
    '        })',
    '',
    '        [void]$win.ShowDialog()',
    '    }',
  ];
}
